--
-- PostgreSQL database dump
--

\restrict gdLRzKZTo1jE9qNC4whwc2Fyg34b3yfjasAHi9zpYhr3QfYKrl8tfBbEXZQhrAO

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: notify_messenger_messages(); Type: FUNCTION; Schema: public; Owner: atelier
--

CREATE FUNCTION public.notify_messenger_messages() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        PERFORM pg_notify('messenger_messages', NEW.queue_name::text);
        RETURN NEW;
    END;
$$;


ALTER FUNCTION public.notify_messenger_messages() OWNER TO atelier;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: absences; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.absences (
    id integer NOT NULL,
    atelier_id integer,
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    motif character varying(50) NOT NULL,
    notes text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    mecanicien_id integer NOT NULL
);


ALTER TABLE public.absences OWNER TO atelier;

--
-- Name: absences_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.absences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: atelier_categorie_motos; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.atelier_categorie_motos (
    id integer NOT NULL,
    atelier_id integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    categorie_moto_id integer NOT NULL
);


ALTER TABLE public.atelier_categorie_motos OWNER TO atelier;

--
-- Name: atelier_categorie_motos_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.atelier_categorie_motos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.atelier_categorie_motos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ateliers; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.ateliers (
    id integer NOT NULL,
    nom character varying(200) NOT NULL,
    slug character varying(100) NOT NULL,
    adresse text,
    cp character varying(20) DEFAULT NULL::character varying,
    ville character varying(100) DEFAULT NULL::character varying,
    telephone character varying(20) DEFAULT NULL::character varying,
    email character varying(200) DEFAULT NULL::character varying,
    siret character varying(20) DEFAULT NULL::character varying,
    tva_intracom character varying(30) DEFAULT NULL::character varying,
    logo_url character varying(500) DEFAULT NULL::character varying,
    plan character varying(50) DEFAULT 'starter'::character varying NOT NULL,
    actif boolean DEFAULT true NOT NULL,
    config_json text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.ateliers OWNER TO atelier;

--
-- Name: ateliers_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.ateliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ateliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.audit_logs (
    id integer NOT NULL,
    atelier_id integer,
    user_id integer,
    username character varying(100) DEFAULT NULL::character varying,
    action character varying(100) NOT NULL,
    entity_type character varying(100) DEFAULT NULL::character varying,
    entity_id integer,
    details text,
    ip_address character varying(50) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.audit_logs OWNER TO atelier;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calculs_tarifs; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.calculs_tarifs (
    id integer NOT NULL,
    prestations_ids text,
    pieces_ids text,
    total_mo_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_pieces_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ttc numeric(10,2) DEFAULT 0.00 NOT NULL,
    marge_pieces numeric(10,2) DEFAULT 0.00 NOT NULL,
    delai_total_jours integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_id integer,
    vehicule_id integer
);


ALTER TABLE public.calculs_tarifs OWNER TO atelier;

--
-- Name: calculs_tarifs_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.calculs_tarifs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calculs_tarifs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorie_motos; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.categorie_motos (
    id integer NOT NULL,
    nom character varying(100) NOT NULL,
    description text,
    is_active integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.categorie_motos OWNER TO atelier;

--
-- Name: categorie_motos_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.categorie_motos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorie_motos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.clients (
    id integer NOT NULL,
    atelier_id integer,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    telephone character varying(20) NOT NULL,
    email character varying(200) DEFAULT NULL::character varying,
    adresse text,
    notes text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.clients OWNER TO atelier;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commandes_fournisseur; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.commandes_fournisseur (
    id integer NOT NULL,
    atelier_id integer,
    numero_commande character varying(50) NOT NULL,
    statut character varying(50) DEFAULT 'en_attente'::character varying NOT NULL,
    date_commande timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_prevue_livraison timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    date_reception timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    total_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ttc numeric(10,2) DEFAULT 0.00 NOT NULL,
    notes text,
    fournisseur_id integer NOT NULL
);


ALTER TABLE public.commandes_fournisseur OWNER TO atelier;

--
-- Name: commandes_fournisseur_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.commandes_fournisseur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commandes_fournisseur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: config_atelier; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.config_atelier (
    id integer NOT NULL,
    atelier_id integer,
    feature_modules json,
    taux_horaire_mo_standard numeric(10,2) DEFAULT 65.00 NOT NULL,
    taux_horaire_mo_complexe numeric(10,2) DEFAULT 85.00 NOT NULL,
    taux_horaire_mo_expert numeric(10,2) DEFAULT 95.00 NOT NULL,
    marge_pieces_standard double precision DEFAULT 30 NOT NULL,
    marge_pieces_consommable double precision DEFAULT 50 NOT NULL,
    marge_pieces_pneumatique double precision DEFAULT 25 NOT NULL,
    forfait_mo_minimum numeric(10,2) DEFAULT 25.00 NOT NULL,
    tva_mo_taux double precision DEFAULT 20 NOT NULL,
    tva_pieces_taux double precision DEFAULT 20 NOT NULL,
    validite_devis_jours integer DEFAULT 30 NOT NULL,
    accompte_pourcentage double precision DEFAULT 30 NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.config_atelier OWNER TO atelier;

--
-- Name: config_atelier_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.config_atelier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.config_atelier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demandes_travaux_supp; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.demandes_travaux_supp (
    id integer NOT NULL,
    description text,
    prestations_demandees text,
    urgence character varying(50) DEFAULT 'normal'::character varying NOT NULL,
    temps_estime integer,
    prix_estime numeric(10,2) DEFAULT NULL::numeric,
    statut character varying(50) DEFAULT 'en_attente'::character varying NOT NULL,
    notes_receptionniste text,
    decision_client character varying(50) DEFAULT NULL::character varying,
    decision_client_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    approved_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    approved_by integer,
    rendez_vous_id integer NOT NULL
);


ALTER TABLE public.demandes_travaux_supp OWNER TO atelier;

--
-- Name: demandes_travaux_supp_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.demandes_travaux_supp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demandes_travaux_supp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devis; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.devis (
    id integer NOT NULL,
    atelier_id integer,
    numero_devis character varying(50) NOT NULL,
    date_creation timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_validite date NOT NULL,
    statut character varying(50) DEFAULT 'brouillon'::character varying NOT NULL,
    kilometrage integer,
    total_mo_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_pieces_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ttc numeric(10,2) DEFAULT 0.00 NOT NULL,
    remise_pourcentage numeric(10,2) DEFAULT 0.00 NOT NULL,
    remise_montant numeric(10,2) DEFAULT 0.00 NOT NULL,
    acompte_demande numeric(10,2) DEFAULT 0.00 NOT NULL,
    notes_client text,
    notes_internes text,
    rendez_vous_id integer,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_id integer NOT NULL,
    vehicule_id integer
);


ALTER TABLE public.devis OWNER TO atelier;

--
-- Name: devis_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.devis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO atelier;

--
-- Name: email_templates; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.email_templates (
    id integer NOT NULL,
    atelier_id integer,
    code character varying(50) NOT NULL,
    nom character varying(200) NOT NULL,
    sujet character varying(500) NOT NULL,
    corps_html text NOT NULL,
    corps_texte text,
    variables_disponibles text,
    is_active integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.email_templates OWNER TO atelier;

--
-- Name: email_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.email_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: factures; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.factures (
    id integer NOT NULL,
    atelier_id integer,
    numero_facture character varying(50) NOT NULL,
    total_mo_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_pieces_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    tva_mo numeric(10,2) DEFAULT 0.00 NOT NULL,
    tva_pieces numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_tva numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ttc numeric(10,2) DEFAULT 0.00 NOT NULL,
    remise_pourcentage numeric(10,2) DEFAULT 0.00 NOT NULL,
    remise_montant numeric(10,2) DEFAULT 0.00 NOT NULL,
    temps_facture_minutes integer DEFAULT 0 NOT NULL,
    taux_horaire numeric(10,2) DEFAULT 65.00 NOT NULL,
    tva_mo_taux double precision DEFAULT 20 NOT NULL,
    tva_pieces_taux double precision DEFAULT 20 NOT NULL,
    statut character varying(50) DEFAULT 'emise'::character varying NOT NULL,
    date_creation timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_echeance date,
    notes text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rendez_vous_id integer NOT NULL,
    client_id integer NOT NULL,
    vehicule_id integer
);


ALTER TABLE public.factures OWNER TO atelier;

--
-- Name: factures_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.factures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forfaits_mo; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.forfaits_mo (
    id integer NOT NULL,
    atelier_id integer,
    code character varying(50) NOT NULL,
    nom character varying(200) NOT NULL,
    description text,
    categorie character varying(100) DEFAULT NULL::character varying,
    temps_base_minutes integer NOT NULL,
    taux_horaire_applique character varying(50) DEFAULT 'standard'::character varying NOT NULL,
    prix_forfait_mo_ht numeric(10,2) NOT NULL,
    prix_forfait_mo_ttc numeric(10,2) NOT NULL,
    inclut_pieces integer DEFAULT 0 NOT NULL,
    description_pieces_incluses text,
    prix_pieces_incluses_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    type_vehicule character varying(50) DEFAULT 'tous'::character varying NOT NULL,
    cylindree_min integer,
    cylindree_max integer,
    is_active integer DEFAULT 1 NOT NULL,
    is_promo integer DEFAULT 0 NOT NULL,
    prix_promo_mo_ttc numeric(10,2) DEFAULT NULL::numeric,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.forfaits_mo OWNER TO atelier;

--
-- Name: forfaits_mo_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.forfaits_mo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forfaits_mo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fournisseurs; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.fournisseurs (
    id integer NOT NULL,
    atelier_id integer,
    nom character varying(200) NOT NULL,
    contact character varying(200) DEFAULT NULL::character varying,
    telephone character varying(20) DEFAULT NULL::character varying,
    email character varying(200) DEFAULT NULL::character varying,
    adresse text,
    siret character varying(20) DEFAULT NULL::character varying,
    delai_livraison_jours integer DEFAULT 3 NOT NULL,
    notes text,
    is_active integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.fournisseurs OWNER TO atelier;

--
-- Name: fournisseurs_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.fournisseurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fournisseurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grille_tarifaire; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.grille_tarifaire (
    id integer NOT NULL,
    atelier_id integer,
    type_vehicule character varying(50) DEFAULT 'tous'::character varying NOT NULL,
    cylindree_min integer,
    cylindree_max integer,
    prix_ht numeric(10,2) NOT NULL,
    prix_ttc numeric(10,2) NOT NULL,
    temps_minutes integer NOT NULL,
    type_tarif character varying(50) DEFAULT 'forfait'::character varying NOT NULL,
    delai_jours integer DEFAULT 1 NOT NULL,
    is_active integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    prestation_id integer NOT NULL,
    categorie_moto_id integer
);


ALTER TABLE public.grille_tarifaire OWNER TO atelier;

--
-- Name: grille_tarifaire_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.grille_tarifaire ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grille_tarifaire_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grille_tarifs; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.grille_tarifs (
    id integer NOT NULL,
    type_intervention character varying(100) NOT NULL,
    nom character varying(200) NOT NULL,
    description text,
    temps_minutes integer NOT NULL,
    prix_mo_ht numeric(10,2) NOT NULL,
    prix_mo_ttc numeric(10,2) NOT NULL,
    pieces_incluses boolean DEFAULT false NOT NULL,
    actif boolean DEFAULT true NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    categorie_moto_id integer
);


ALTER TABLE public.grille_tarifs OWNER TO atelier;

--
-- Name: grille_tarifs_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.grille_tarifs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grille_tarifs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: horaires_atelier; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.horaires_atelier (
    id integer NOT NULL,
    atelier_id integer,
    jour_semaine integer NOT NULL,
    heure_ouverture character varying(5) DEFAULT NULL::character varying,
    heure_fermeture character varying(5) DEFAULT NULL::character varying,
    pause_debut character varying(5) DEFAULT NULL::character varying,
    pause_fin character varying(5) DEFAULT NULL::character varying,
    is_ouvert integer DEFAULT 1 NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.horaires_atelier OWNER TO atelier;

--
-- Name: horaires_atelier_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.horaires_atelier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.horaires_atelier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: intervention_types; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.intervention_types (
    id integer NOT NULL,
    nom character varying(200) NOT NULL,
    description text,
    prix_base numeric(10,2) NOT NULL,
    temps_estime integer NOT NULL,
    is_active integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.intervention_types OWNER TO atelier;

--
-- Name: intervention_types_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.intervention_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.intervention_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lignes_commande_fournisseur; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.lignes_commande_fournisseur (
    id integer NOT NULL,
    atelier_id integer,
    quantite_demandee integer NOT NULL,
    quantite_recue integer DEFAULT 0 NOT NULL,
    prix_unitaire_ht numeric(10,2) NOT NULL,
    commande_id integer NOT NULL,
    piece_id integer NOT NULL
);


ALTER TABLE public.lignes_commande_fournisseur OWNER TO atelier;

--
-- Name: lignes_commande_fournisseur_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.lignes_commande_fournisseur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lignes_commande_fournisseur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lignes_devis; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.lignes_devis (
    id integer NOT NULL,
    type_ligne character varying(50) NOT NULL,
    designation character varying(300) NOT NULL,
    description_detail text,
    quantite integer DEFAULT 1 NOT NULL,
    prix_unitaire_ht numeric(10,2) NOT NULL,
    taux_tva double precision DEFAULT 20 NOT NULL,
    total_ligne_ht numeric(10,2) NOT NULL,
    total_ligne_ttc numeric(10,2) NOT NULL,
    ordre integer DEFAULT 0 NOT NULL,
    devis_id integer NOT NULL,
    forfait_mo_id integer,
    piece_id integer
);


ALTER TABLE public.lignes_devis OWNER TO atelier;

--
-- Name: lignes_devis_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.lignes_devis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lignes_devis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lignes_facture; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.lignes_facture (
    id integer NOT NULL,
    atelier_id integer,
    type_ligne character varying(50) NOT NULL,
    designation character varying(300) NOT NULL,
    reference character varying(100) DEFAULT NULL::character varying,
    quantite double precision DEFAULT 1 NOT NULL,
    prix_unitaire_ht numeric(10,2) NOT NULL,
    taux_tva double precision DEFAULT 20 NOT NULL,
    total_ligne_ht numeric(10,2) NOT NULL,
    total_ligne_ttc numeric(10,2) NOT NULL,
    ordre integer DEFAULT 0 NOT NULL,
    facture_id integer NOT NULL
);


ALTER TABLE public.lignes_facture OWNER TO atelier;

--
-- Name: lignes_facture_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.lignes_facture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lignes_facture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mecaniciens; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.mecaniciens (
    id integer NOT NULL,
    atelier_id integer,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    specialites text,
    couleur character varying(7) DEFAULT '#3b82f6'::character varying NOT NULL,
    is_active integer DEFAULT 1 NOT NULL,
    user_id integer
);


ALTER TABLE public.mecaniciens OWNER TO atelier;

--
-- Name: mecaniciens_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.mecaniciens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mecaniciens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO atelier;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modele_motos; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.modele_motos (
    id integer NOT NULL,
    marque character varying(100) NOT NULL,
    modele character varying(100) NOT NULL,
    cylindree_min integer,
    cylindree_max integer,
    annee_debut integer,
    annee_fin integer,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    categorie_id integer NOT NULL
);


ALTER TABLE public.modele_motos OWNER TO atelier;

--
-- Name: modele_motos_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.modele_motos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modele_motos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moto_technical_specs; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.moto_technical_specs (
    id integer NOT NULL,
    variante character varying(150) DEFAULT NULL::character varying,
    annee_debut integer NOT NULL,
    annee_fin integer,
    source character varying(255) DEFAULT NULL::character varying,
    general_json text DEFAULT '{}'::text NOT NULL,
    moteur_json text DEFAULT '{}'::text NOT NULL,
    pneumatique_json text DEFAULT '{}'::text NOT NULL,
    freinage_json text DEFAULT '{}'::text NOT NULL,
    suspension_json text DEFAULT '{}'::text NOT NULL,
    systemes_electriques_json text DEFAULT '{}'::text NOT NULL,
    entretien_json text DEFAULT '{}'::text NOT NULL,
    notes text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modele_moto_id integer NOT NULL
);


ALTER TABLE public.moto_technical_specs OWNER TO atelier;

--
-- Name: moto_technical_specs_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.moto_technical_specs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moto_technical_specs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordres_reparation; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.ordres_reparation (
    id integer NOT NULL,
    numero_or character varying(50) NOT NULL,
    type_or character varying(50) DEFAULT 'initial'::character varying NOT NULL,
    kilometrage integer,
    etat_vehicule text,
    travaux text,
    signature_client text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rendez_vous_id integer NOT NULL,
    demande_travaux_supp_id integer
);


ALTER TABLE public.ordres_reparation OWNER TO atelier;

--
-- Name: ordres_reparation_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.ordres_reparation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordres_reparation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paiements; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.paiements (
    id integer NOT NULL,
    montant numeric(10,2) NOT NULL,
    mode_paiement character varying(50) NOT NULL,
    reference character varying(200) DEFAULT NULL::character varying,
    date_paiement timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    notes text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    facture_id integer NOT NULL
);


ALTER TABLE public.paiements OWNER TO atelier;

--
-- Name: paiements_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.paiements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paiements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photos_intervention; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.photos_intervention (
    id integer NOT NULL,
    atelier_id integer,
    filename character varying(300) NOT NULL,
    original_name character varying(300) DEFAULT NULL::character varying,
    annotation_json text,
    description text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rendez_vous_id integer NOT NULL
);


ALTER TABLE public.photos_intervention OWNER TO atelier;

--
-- Name: photos_intervention_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.photos_intervention ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photos_intervention_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pieces_detachees; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.pieces_detachees (
    id integer NOT NULL,
    atelier_id integer,
    reference character varying(100) NOT NULL,
    reference_fournisseur character varying(100) DEFAULT NULL::character varying,
    nom character varying(200) NOT NULL,
    description text,
    categorie character varying(100) DEFAULT NULL::character varying,
    quantite_stock integer DEFAULT 0 NOT NULL,
    quantite_minimale integer DEFAULT 5 NOT NULL,
    quantite_maximale integer DEFAULT 50 NOT NULL,
    emplacement character varying(100) DEFAULT NULL::character varying,
    prix_achat_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    prix_vente_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    tva_taux double precision DEFAULT 20 NOT NULL,
    is_active integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fournisseur_id integer
);


ALTER TABLE public.pieces_detachees OWNER TO atelier;

--
-- Name: pieces_detachees_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.pieces_detachees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pieces_detachees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pieces_utilisees; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.pieces_utilisees (
    id integer NOT NULL,
    quantite integer NOT NULL,
    prix_vente_unitaire numeric(10,2) DEFAULT NULL::numeric,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rendez_vous_id integer NOT NULL,
    piece_id integer NOT NULL
);


ALTER TABLE public.pieces_utilisees OWNER TO atelier;

--
-- Name: pieces_utilisees_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.pieces_utilisees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pieces_utilisees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pont_equipements; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.pont_equipements (
    id integer NOT NULL,
    nom character varying(200) NOT NULL,
    description text,
    is_present boolean DEFAULT true NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    pont_id integer NOT NULL
);


ALTER TABLE public.pont_equipements OWNER TO atelier;

--
-- Name: pont_equipements_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.pont_equipements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pont_equipements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ponts; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.ponts (
    id integer NOT NULL,
    atelier_id integer,
    nom character varying(100) NOT NULL,
    type_pont character varying(50) DEFAULT 'moto'::character varying NOT NULL,
    capacite_kg integer DEFAULT 500 NOT NULL,
    is_active integer DEFAULT 1 NOT NULL,
    ordre_affichage integer DEFAULT 0 NOT NULL,
    mecanicien_id integer
);


ALTER TABLE public.ponts OWNER TO atelier;

--
-- Name: ponts_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.ponts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ponts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prestations; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.prestations (
    id integer NOT NULL,
    atelier_id integer,
    code character varying(50) NOT NULL,
    nom character varying(200) NOT NULL,
    description text,
    categorie character varying(100) DEFAULT 'entretien'::character varying NOT NULL,
    sous_categorie character varying(100) DEFAULT NULL::character varying,
    prix_base_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    prix_base_ttc numeric(10,2) DEFAULT 0.00 NOT NULL,
    temps_estime_minutes integer DEFAULT 30 NOT NULL,
    delai_intervention_jours integer DEFAULT 1 NOT NULL,
    type_tarif character varying(50) DEFAULT 'forfait'::character varying NOT NULL,
    taux_horaire_applique character varying(50) DEFAULT 'standard'::character varying NOT NULL,
    type_vehicule character varying(50) DEFAULT 'tous'::character varying NOT NULL,
    cylindree_min integer,
    cylindree_max integer,
    is_active integer DEFAULT 1 NOT NULL,
    is_forfait integer DEFAULT 0 NOT NULL,
    is_promo integer DEFAULT 0 NOT NULL,
    prix_promo_ttc numeric(10,2) DEFAULT NULL::numeric,
    inclut_pieces integer DEFAULT 0 NOT NULL,
    description_pieces_incluses text,
    cout_pieces_incluses_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    marge_pieces_pourcent double precision DEFAULT 30 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.prestations OWNER TO atelier;

--
-- Name: prestations_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.prestations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prestations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rappels_email; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.rappels_email (
    id integer NOT NULL,
    atelier_id integer NOT NULL,
    type_rappel character varying(50) NOT NULL,
    destinataire character varying(200) NOT NULL,
    sujet character varying(500) DEFAULT NULL::character varying,
    statut character varying(30) DEFAULT 'programme'::character varying NOT NULL,
    erreur text,
    date_envoi_prevu timestamp(0) without time zone NOT NULL,
    date_envoi_reel timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rdv_id integer NOT NULL,
    client_id integer NOT NULL
);


ALTER TABLE public.rappels_email OWNER TO atelier;

--
-- Name: rappels_email_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.rappels_email ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rappels_email_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rapports_technicien; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.rapports_technicien (
    id integer NOT NULL,
    points_controle text DEFAULT '{}'::text NOT NULL,
    alertes text,
    recommandations text,
    travaux_realises text,
    pieces_utilisees text DEFAULT '[]'::text NOT NULL,
    statut character varying(50) DEFAULT 'en_cours'::character varying NOT NULL,
    date_debut timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_fin timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    rendez_vous_id integer NOT NULL
);


ALTER TABLE public.rapports_technicien OWNER TO atelier;

--
-- Name: rapports_technicien_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.rapports_technicien ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rapports_technicien_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rendez_vous; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.rendez_vous (
    id integer NOT NULL,
    atelier_id integer,
    date_rdv date NOT NULL,
    heure_rdv time(0) without time zone NOT NULL,
    type_intervention character varying(200) NOT NULL,
    commentaire text,
    prix_estime numeric(10,2) DEFAULT NULL::numeric,
    prix_final numeric(10,2) DEFAULT NULL::numeric,
    temps_estime integer,
    temps_final integer,
    heure_debut_travail timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    heure_fin_travail timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    temps_effectif_minutes integer,
    kilometrage integer,
    etat_vehicule text,
    photos_etat text,
    statut character varying(50) DEFAULT 'en_attente'::character varying NOT NULL,
    token_suivi character varying(64) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_id integer,
    vehicule_id integer,
    pont_id integer,
    mecanicien_id integer
);


ALTER TABLE public.rendez_vous OWNER TO atelier;

--
-- Name: rendez_vous_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.rendez_vous ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rendez_vous_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revoked_tokens; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.revoked_tokens (
    id integer NOT NULL,
    jti character varying(255) NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    reason character varying(100) DEFAULT 'manual'::character varying NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.revoked_tokens OWNER TO atelier;

--
-- Name: revoked_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.revoked_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revoked_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.role_permissions (
    role character varying(50) NOT NULL,
    label character varying(120) NOT NULL,
    description text,
    sections_json text DEFAULT '[]'::text NOT NULL,
    permissions_json text DEFAULT '[]'::text NOT NULL,
    is_system integer DEFAULT 0 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO atelier;

--
-- Name: temps_interventions; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.temps_interventions (
    id integer NOT NULL,
    temps_minutes integer NOT NULL,
    coefficient_difficulte double precision DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    categorie_moto_id integer NOT NULL,
    intervention_type_id integer NOT NULL
);


ALTER TABLE public.temps_interventions OWNER TO atelier;

--
-- Name: temps_interventions_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.temps_interventions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.temps_interventions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_atelier_roles; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.user_atelier_roles (
    user_id integer NOT NULL,
    atelier_id integer NOT NULL,
    role character varying(50) DEFAULT 'receptionnaire'::character varying NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.user_atelier_roles OWNER TO atelier;

--
-- Name: users; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.users (
    id integer NOT NULL,
    atelier_id integer,
    username character varying(100) NOT NULL,
    email character varying(200) NOT NULL,
    hashed_password character varying(200) NOT NULL,
    role character varying(50) DEFAULT 'receptionnaire'::character varying NOT NULL,
    is_active integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.users OWNER TO atelier;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicules; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.vehicules (
    id integer NOT NULL,
    atelier_id integer,
    plaque character varying(20) NOT NULL,
    marque character varying(100) DEFAULT NULL::character varying,
    modele character varying(100) DEFAULT NULL::character varying,
    annee integer,
    cylindree character varying(50) DEFAULT NULL::character varying,
    type_moto character varying(50) DEFAULT NULL::character varying,
    client_id integer,
    categorie_id integer,
    modele_id integer
);


ALTER TABLE public.vehicules OWNER TO atelier;

--
-- Name: vehicules_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.vehicules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: absences; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.absences (id, atelier_id, date_debut, date_fin, motif, notes, created_at, mecanicien_id) FROM stdin;
\.


--
-- Data for Name: atelier_categorie_motos; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.atelier_categorie_motos (id, atelier_id, is_active, created_at, updated_at, categorie_moto_id) FROM stdin;
\.


--
-- Data for Name: ateliers; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.ateliers (id, nom, slug, adresse, cp, ville, telephone, email, siret, tva_intracom, logo_url, plan, actif, config_json, created_at) FROM stdin;
1	Atelier Principal	atelier-principal	\N	\N	\N	\N	\N	\N	\N	\N	starter	t	\N	2026-04-16 07:07:10
\.


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.audit_logs (id, atelier_id, user_id, username, action, entity_type, entity_id, details, ip_address, created_at) FROM stdin;
\.


--
-- Data for Name: calculs_tarifs; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.calculs_tarifs (id, prestations_ids, pieces_ids, total_mo_ht, total_pieces_ht, total_ht, total_ttc, marge_pieces, delai_total_jours, created_at, client_id, vehicule_id) FROM stdin;
\.


--
-- Data for Name: categorie_motos; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.categorie_motos (id, nom, description, is_active, created_at) FROM stdin;
1	Roadster	\N	1	2026-04-16 07:07:09
2	Sportive	\N	1	2026-04-16 07:07:09
3	Trail	\N	1	2026-04-16 07:07:09
4	Touring	\N	1	2026-04-16 07:07:09
5	Custom	\N	1	2026-04-16 07:07:09
6	Scooter	\N	1	2026-04-16 07:07:09
7	Enduro	\N	1	2026-04-16 07:07:09
8	Supermotard	\N	1	2026-04-16 07:07:09
9	Vintage	\N	1	2026-04-16 07:07:09
10	Électrique	\N	1	2026-04-16 07:07:09
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.clients (id, atelier_id, nom, prenom, telephone, email, adresse, notes, created_at) FROM stdin;
\.


--
-- Data for Name: commandes_fournisseur; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.commandes_fournisseur (id, atelier_id, numero_commande, statut, date_commande, date_prevue_livraison, date_reception, total_ht, total_ttc, notes, fournisseur_id) FROM stdin;
\.


--
-- Data for Name: config_atelier; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.config_atelier (id, atelier_id, feature_modules, taux_horaire_mo_standard, taux_horaire_mo_complexe, taux_horaire_mo_expert, marge_pieces_standard, marge_pieces_consommable, marge_pieces_pneumatique, forfait_mo_minimum, tva_mo_taux, tva_pieces_taux, validite_devis_jours, accompte_pourcentage, updated_at) FROM stdin;
1	1	{"dashboard":true,"rdv":true,"planning":true,"workshop":true,"suivi":true,"clients":true,"or":true,"motos":true,"devis":true,"facturation":true,"stock":true,"mecanicien":true,"absences":true,"admin":true,"tarifs":true}	65.00	85.00	95.00	30	50	25	25.00	20	20	30	30	2026-04-16 07:07:09
\.


--
-- Data for Name: demandes_travaux_supp; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.demandes_travaux_supp (id, description, prestations_demandees, urgence, temps_estime, prix_estime, statut, notes_receptionniste, decision_client, decision_client_at, created_at, approved_at, approved_by, rendez_vous_id) FROM stdin;
\.


--
-- Data for Name: devis; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.devis (id, atelier_id, numero_devis, date_creation, date_validite, statut, kilometrage, total_mo_ht, total_pieces_ht, total_ht, total_ttc, remise_pourcentage, remise_montant, acompte_demande, notes_client, notes_internes, rendez_vous_id, created_at, updated_at, client_id, vehicule_id) FROM stdin;
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
\.


--
-- Data for Name: email_templates; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.email_templates (id, atelier_id, code, nom, sujet, corps_html, corps_texte, variables_disponibles, is_active, created_at, updated_at) FROM stdin;
1	1	confirmation	Confirmation RDV	Confirmation de votre rendez-vous du {{date_rdv}}	<p>Bonjour {{client_prenom}} {{client_nom}},</p><p>Votre rendez-vous du <strong>{{date_rdv}}</strong> à <strong>{{heure_rdv}}</strong> pour <em>{{type_intervention}}</em> est confirmé.</p><p>Suivez l'avancement : <a href="{{url_suivi}}">Suivi en ligne</a></p>	\N	["client_nom","client_prenom","date_rdv","heure_rdv","type_intervention","token_suivi","url_suivi"]	1	2026-04-16 07:07:10	2026-04-16 07:07:10
2	1	rappel_j3	Rappel J-3	Rappel : votre rendez-vous dans 3 jours	<p>Bonjour {{client_prenom}},</p><p>Rappel : votre rendez-vous est prévu dans 3 jours, le <strong>{{date_rdv}}</strong> à <strong>{{heure_rdv}}</strong>.</p>	\N	["client_nom","client_prenom","date_rdv","heure_rdv","type_intervention","token_suivi","url_suivi"]	1	2026-04-16 07:07:10	2026-04-16 07:07:10
3	1	rappel_j1	Rappel J-1	Rappel : votre rendez-vous demain	<p>Bonjour {{client_prenom}},</p><p>Rappel : votre rendez-vous est <strong>demain</strong> le {{date_rdv}} à {{heure_rdv}}.</p>	\N	["client_nom","client_prenom","date_rdv","heure_rdv","type_intervention","token_suivi","url_suivi"]	1	2026-04-16 07:07:10	2026-04-16 07:07:10
4	1	travaux_termines	Travaux terminés	Votre moto est prête !	<p>Bonjour {{client_prenom}},</p><p>Les travaux sur votre véhicule sont terminés. Vous pouvez venir le récupérer.</p>	\N	["client_nom","client_prenom","date_rdv","heure_rdv","type_intervention","token_suivi","url_suivi"]	1	2026-04-16 07:07:10	2026-04-16 07:07:10
\.


--
-- Data for Name: factures; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.factures (id, atelier_id, numero_facture, total_mo_ht, total_pieces_ht, total_ht, tva_mo, tva_pieces, total_tva, total_ttc, remise_pourcentage, remise_montant, temps_facture_minutes, taux_horaire, tva_mo_taux, tva_pieces_taux, statut, date_creation, date_echeance, notes, created_at, updated_at, rendez_vous_id, client_id, vehicule_id) FROM stdin;
\.


--
-- Data for Name: forfaits_mo; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.forfaits_mo (id, atelier_id, code, nom, description, categorie, temps_base_minutes, taux_horaire_applique, prix_forfait_mo_ht, prix_forfait_mo_ttc, inclut_pieces, description_pieces_incluses, prix_pieces_incluses_ht, type_vehicule, cylindree_min, cylindree_max, is_active, is_promo, prix_promo_mo_ttc, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: fournisseurs; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.fournisseurs (id, atelier_id, nom, contact, telephone, email, adresse, siret, delai_livraison_jours, notes, is_active, created_at) FROM stdin;
\.


--
-- Data for Name: grille_tarifaire; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.grille_tarifaire (id, atelier_id, type_vehicule, cylindree_min, cylindree_max, prix_ht, prix_ttc, temps_minutes, type_tarif, delai_jours, is_active, created_at, prestation_id, categorie_moto_id) FROM stdin;
\.


--
-- Data for Name: grille_tarifs; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.grille_tarifs (id, type_intervention, nom, description, temps_minutes, prix_mo_ht, prix_mo_ttc, pieces_incluses, actif, created_at, categorie_moto_id) FROM stdin;
\.


--
-- Data for Name: horaires_atelier; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.horaires_atelier (id, atelier_id, jour_semaine, heure_ouverture, heure_fermeture, pause_debut, pause_fin, is_ouvert, updated_at) FROM stdin;
1	1	0	08:00	18:00	12:00	13:30	1	2026-04-16 07:07:09
2	1	1	08:00	18:00	12:00	13:30	1	2026-04-16 07:07:09
3	1	2	08:00	18:00	12:00	13:30	1	2026-04-16 07:07:09
4	1	3	08:00	18:00	12:00	13:30	1	2026-04-16 07:07:09
5	1	4	08:00	18:00	12:00	13:30	1	2026-04-16 07:07:09
6	1	5	09:00	13:00	\N	\N	1	2026-04-16 07:07:09
7	1	6	\N	\N	\N	\N	0	2026-04-16 07:07:09
\.


--
-- Data for Name: intervention_types; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.intervention_types (id, nom, description, prix_base, temps_estime, is_active) FROM stdin;
\.


--
-- Data for Name: lignes_commande_fournisseur; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.lignes_commande_fournisseur (id, atelier_id, quantite_demandee, quantite_recue, prix_unitaire_ht, commande_id, piece_id) FROM stdin;
\.


--
-- Data for Name: lignes_devis; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.lignes_devis (id, type_ligne, designation, description_detail, quantite, prix_unitaire_ht, taux_tva, total_ligne_ht, total_ligne_ttc, ordre, devis_id, forfait_mo_id, piece_id) FROM stdin;
\.


--
-- Data for Name: lignes_facture; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.lignes_facture (id, atelier_id, type_ligne, designation, reference, quantite, prix_unitaire_ht, taux_tva, total_ligne_ht, total_ligne_ttc, ordre, facture_id) FROM stdin;
\.


--
-- Data for Name: mecaniciens; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.mecaniciens (id, atelier_id, nom, prenom, specialites, couleur, is_active, user_id) FROM stdin;
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: modele_motos; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.modele_motos (id, marque, modele, cylindree_min, cylindree_max, annee_debut, annee_fin, created_at, updated_at, categorie_id) FROM stdin;
\.


--
-- Data for Name: moto_technical_specs; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.moto_technical_specs (id, variante, annee_debut, annee_fin, source, general_json, moteur_json, pneumatique_json, freinage_json, suspension_json, systemes_electriques_json, entretien_json, notes, created_at, updated_at, modele_moto_id) FROM stdin;
\.


--
-- Data for Name: ordres_reparation; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.ordres_reparation (id, numero_or, type_or, kilometrage, etat_vehicule, travaux, signature_client, created_at, rendez_vous_id, demande_travaux_supp_id) FROM stdin;
\.


--
-- Data for Name: paiements; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.paiements (id, montant, mode_paiement, reference, date_paiement, notes, created_at, facture_id) FROM stdin;
\.


--
-- Data for Name: photos_intervention; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.photos_intervention (id, atelier_id, filename, original_name, annotation_json, description, created_at, rendez_vous_id) FROM stdin;
\.


--
-- Data for Name: pieces_detachees; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.pieces_detachees (id, atelier_id, reference, reference_fournisseur, nom, description, categorie, quantite_stock, quantite_minimale, quantite_maximale, emplacement, prix_achat_ht, prix_vente_ht, tva_taux, is_active, created_at, updated_at, fournisseur_id) FROM stdin;
\.


--
-- Data for Name: pieces_utilisees; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.pieces_utilisees (id, quantite, prix_vente_unitaire, created_at, rendez_vous_id, piece_id) FROM stdin;
\.


--
-- Data for Name: pont_equipements; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.pont_equipements (id, nom, description, is_present, created_at, updated_at, pont_id) FROM stdin;
\.


--
-- Data for Name: ponts; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.ponts (id, atelier_id, nom, type_pont, capacite_kg, is_active, ordre_affichage, mecanicien_id) FROM stdin;
\.


--
-- Data for Name: prestations; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.prestations (id, atelier_id, code, nom, description, categorie, sous_categorie, prix_base_ht, prix_base_ttc, temps_estime_minutes, delai_intervention_jours, type_tarif, taux_horaire_applique, type_vehicule, cylindree_min, cylindree_max, is_active, is_forfait, is_promo, prix_promo_ttc, inclut_pieces, description_pieces_incluses, cout_pieces_incluses_ht, marge_pieces_pourcent, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: rappels_email; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.rappels_email (id, atelier_id, type_rappel, destinataire, sujet, statut, erreur, date_envoi_prevu, date_envoi_reel, created_at, rdv_id, client_id) FROM stdin;
\.


--
-- Data for Name: rapports_technicien; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.rapports_technicien (id, points_controle, alertes, recommandations, travaux_realises, pieces_utilisees, statut, date_debut, date_fin, rendez_vous_id) FROM stdin;
\.


--
-- Data for Name: rendez_vous; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.rendez_vous (id, atelier_id, date_rdv, heure_rdv, type_intervention, commentaire, prix_estime, prix_final, temps_estime, temps_final, heure_debut_travail, heure_fin_travail, temps_effectif_minutes, kilometrage, etat_vehicule, photos_etat, statut, token_suivi, created_at, updated_at, client_id, vehicule_id, pont_id, mecanicien_id) FROM stdin;
\.


--
-- Data for Name: revoked_tokens; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.revoked_tokens (id, jti, expires_at, reason, created_at) FROM stdin;
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.role_permissions (role, label, description, sections_json, permissions_json, is_system, created_at, updated_at) FROM stdin;
super_admin	Super Admin	Accès total à tous les ateliers	["*"]	["*"]	1	2026-04-16 07:07:09	2026-04-16 07:07:09
admin	Administrateur	Gestion complète de l'atelier	["dashboard","rdv","planning","clients","workshop","or","devis","facturation","stock","motos","admin","mecanicien","absences","suivi"]	["rdv.create","rdv.edit","rdv.delete","client.create","client.edit","client.delete","facturation.create","facturation.edit","stock.create","stock.edit","stock.delete","admin.users","admin.config"]	1	2026-04-16 07:07:09	2026-04-16 07:07:09
receptionnaire	Réceptionnaire	Gestion RDV, clients, facturation	["dashboard","rdv","planning","clients","workshop","or","devis","facturation","suivi"]	["rdv.create","rdv.edit","client.create","client.edit","facturation.create","facturation.edit"]	1	2026-04-16 07:07:09	2026-04-16 07:07:09
mecanicien	Mécanicien	Espace technicien, rapports	["mecanicien","suivi"]	["rdv.edit","or.edit"]	1	2026-04-16 07:07:09	2026-04-16 07:07:09
comptable	Comptable	Facturation et statistiques	["dashboard","facturation","stock"]	["facturation.create","facturation.edit","stock.edit"]	1	2026-04-16 07:07:09	2026-04-16 07:07:09
\.


--
-- Data for Name: temps_interventions; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.temps_interventions (id, temps_minutes, coefficient_difficulte, created_at, updated_at, categorie_moto_id, intervention_type_id) FROM stdin;
\.


--
-- Data for Name: user_atelier_roles; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.user_atelier_roles (user_id, atelier_id, role, created_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.users (id, atelier_id, username, email, hashed_password, role, is_active, created_at) FROM stdin;
1	1	admin	admin@atelier.local	$2y$13$wSUMSpBL0/ojP6zHk2Hpv.lqBOOCDsu5Cu8HA7qRfuBz1bn3SXztK	super_admin	1	2026-04-16 07:07:10
\.


--
-- Data for Name: vehicules; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.vehicules (id, atelier_id, plaque, marque, modele, annee, cylindree, type_moto, client_id, categorie_id, modele_id) FROM stdin;
\.


--
-- Name: absences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.absences_id_seq', 1, false);


--
-- Name: atelier_categorie_motos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.atelier_categorie_motos_id_seq', 1, false);


--
-- Name: ateliers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.ateliers_id_seq', 1, true);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 1, false);


--
-- Name: calculs_tarifs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.calculs_tarifs_id_seq', 1, false);


--
-- Name: categorie_motos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.categorie_motos_id_seq', 10, true);


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.clients_id_seq', 1, false);


--
-- Name: commandes_fournisseur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.commandes_fournisseur_id_seq', 1, false);


--
-- Name: config_atelier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.config_atelier_id_seq', 1, true);


--
-- Name: demandes_travaux_supp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.demandes_travaux_supp_id_seq', 1, false);


--
-- Name: devis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.devis_id_seq', 1, false);


--
-- Name: email_templates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.email_templates_id_seq', 4, true);


--
-- Name: factures_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.factures_id_seq', 1, false);


--
-- Name: forfaits_mo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.forfaits_mo_id_seq', 1, false);


--
-- Name: fournisseurs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.fournisseurs_id_seq', 1, false);


--
-- Name: grille_tarifaire_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.grille_tarifaire_id_seq', 1, false);


--
-- Name: grille_tarifs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.grille_tarifs_id_seq', 1, false);


--
-- Name: horaires_atelier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.horaires_atelier_id_seq', 7, true);


--
-- Name: intervention_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.intervention_types_id_seq', 1, false);


--
-- Name: lignes_commande_fournisseur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.lignes_commande_fournisseur_id_seq', 1, false);


--
-- Name: lignes_devis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.lignes_devis_id_seq', 1, false);


--
-- Name: lignes_facture_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.lignes_facture_id_seq', 1, false);


--
-- Name: mecaniciens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.mecaniciens_id_seq', 1, false);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: modele_motos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.modele_motos_id_seq', 1, false);


--
-- Name: moto_technical_specs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.moto_technical_specs_id_seq', 1, false);


--
-- Name: ordres_reparation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.ordres_reparation_id_seq', 1, false);


--
-- Name: paiements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.paiements_id_seq', 1, false);


--
-- Name: photos_intervention_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.photos_intervention_id_seq', 1, false);


--
-- Name: pieces_detachees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.pieces_detachees_id_seq', 1, false);


--
-- Name: pieces_utilisees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.pieces_utilisees_id_seq', 1, false);


--
-- Name: pont_equipements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.pont_equipements_id_seq', 1, false);


--
-- Name: ponts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.ponts_id_seq', 1, false);


--
-- Name: prestations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.prestations_id_seq', 1, false);


--
-- Name: rappels_email_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.rappels_email_id_seq', 1, false);


--
-- Name: rapports_technicien_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.rapports_technicien_id_seq', 1, false);


--
-- Name: rendez_vous_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.rendez_vous_id_seq', 1, false);


--
-- Name: revoked_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.revoked_tokens_id_seq', 1, false);


--
-- Name: temps_interventions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.temps_interventions_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: vehicules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.vehicules_id_seq', 1, false);


--
-- Name: absences absences_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.absences
    ADD CONSTRAINT absences_pkey PRIMARY KEY (id);


--
-- Name: atelier_categorie_motos atelier_categorie_motos_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.atelier_categorie_motos
    ADD CONSTRAINT atelier_categorie_motos_pkey PRIMARY KEY (id);


--
-- Name: ateliers ateliers_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.ateliers
    ADD CONSTRAINT ateliers_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: calculs_tarifs calculs_tarifs_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.calculs_tarifs
    ADD CONSTRAINT calculs_tarifs_pkey PRIMARY KEY (id);


--
-- Name: categorie_motos categorie_motos_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.categorie_motos
    ADD CONSTRAINT categorie_motos_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: commandes_fournisseur commandes_fournisseur_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.commandes_fournisseur
    ADD CONSTRAINT commandes_fournisseur_pkey PRIMARY KEY (id);


--
-- Name: config_atelier config_atelier_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.config_atelier
    ADD CONSTRAINT config_atelier_pkey PRIMARY KEY (id);


--
-- Name: demandes_travaux_supp demandes_travaux_supp_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.demandes_travaux_supp
    ADD CONSTRAINT demandes_travaux_supp_pkey PRIMARY KEY (id);


--
-- Name: devis devis_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.devis
    ADD CONSTRAINT devis_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: email_templates email_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);


--
-- Name: factures factures_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT factures_pkey PRIMARY KEY (id);


--
-- Name: forfaits_mo forfaits_mo_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.forfaits_mo
    ADD CONSTRAINT forfaits_mo_pkey PRIMARY KEY (id);


--
-- Name: fournisseurs fournisseurs_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT fournisseurs_pkey PRIMARY KEY (id);


--
-- Name: grille_tarifaire grille_tarifaire_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.grille_tarifaire
    ADD CONSTRAINT grille_tarifaire_pkey PRIMARY KEY (id);


--
-- Name: grille_tarifs grille_tarifs_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.grille_tarifs
    ADD CONSTRAINT grille_tarifs_pkey PRIMARY KEY (id);


--
-- Name: horaires_atelier horaires_atelier_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.horaires_atelier
    ADD CONSTRAINT horaires_atelier_pkey PRIMARY KEY (id);


--
-- Name: intervention_types intervention_types_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.intervention_types
    ADD CONSTRAINT intervention_types_pkey PRIMARY KEY (id);


--
-- Name: lignes_commande_fournisseur lignes_commande_fournisseur_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_commande_fournisseur
    ADD CONSTRAINT lignes_commande_fournisseur_pkey PRIMARY KEY (id);


--
-- Name: lignes_devis lignes_devis_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_devis
    ADD CONSTRAINT lignes_devis_pkey PRIMARY KEY (id);


--
-- Name: lignes_facture lignes_facture_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_facture
    ADD CONSTRAINT lignes_facture_pkey PRIMARY KEY (id);


--
-- Name: mecaniciens mecaniciens_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.mecaniciens
    ADD CONSTRAINT mecaniciens_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: modele_motos modele_motos_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.modele_motos
    ADD CONSTRAINT modele_motos_pkey PRIMARY KEY (id);


--
-- Name: moto_technical_specs moto_technical_specs_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.moto_technical_specs
    ADD CONSTRAINT moto_technical_specs_pkey PRIMARY KEY (id);


--
-- Name: ordres_reparation ordres_reparation_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.ordres_reparation
    ADD CONSTRAINT ordres_reparation_pkey PRIMARY KEY (id);


--
-- Name: paiements paiements_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.paiements
    ADD CONSTRAINT paiements_pkey PRIMARY KEY (id);


--
-- Name: photos_intervention photos_intervention_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.photos_intervention
    ADD CONSTRAINT photos_intervention_pkey PRIMARY KEY (id);


--
-- Name: pieces_detachees pieces_detachees_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.pieces_detachees
    ADD CONSTRAINT pieces_detachees_pkey PRIMARY KEY (id);


--
-- Name: pieces_utilisees pieces_utilisees_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.pieces_utilisees
    ADD CONSTRAINT pieces_utilisees_pkey PRIMARY KEY (id);


--
-- Name: pont_equipements pont_equipements_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.pont_equipements
    ADD CONSTRAINT pont_equipements_pkey PRIMARY KEY (id);


--
-- Name: ponts ponts_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.ponts
    ADD CONSTRAINT ponts_pkey PRIMARY KEY (id);


--
-- Name: prestations prestations_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.prestations
    ADD CONSTRAINT prestations_pkey PRIMARY KEY (id);


--
-- Name: rappels_email rappels_email_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rappels_email
    ADD CONSTRAINT rappels_email_pkey PRIMARY KEY (id);


--
-- Name: rapports_technicien rapports_technicien_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rapports_technicien
    ADD CONSTRAINT rapports_technicien_pkey PRIMARY KEY (id);


--
-- Name: rendez_vous rendez_vous_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT rendez_vous_pkey PRIMARY KEY (id);


--
-- Name: revoked_tokens revoked_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.revoked_tokens
    ADD CONSTRAINT revoked_tokens_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role);


--
-- Name: temps_interventions temps_interventions_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.temps_interventions
    ADD CONSTRAINT temps_interventions_pkey PRIMARY KEY (id);


--
-- Name: user_atelier_roles user_atelier_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.user_atelier_roles
    ADD CONSTRAINT user_atelier_roles_pkey PRIMARY KEY (user_id, atelier_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vehicules vehicules_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.vehicules
    ADD CONSTRAINT vehicules_pkey PRIMARY KEY (id);


--
-- Name: idx_199806c9bcf5e72d; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_199806c9bcf5e72d ON public.modele_motos USING btree (categorie_id);


--
-- Name: idx_20160e347b8c1e64; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_20160e347b8c1e64 ON public.ordres_reparation USING btree (demande_travaux_supp_id);


--
-- Name: idx_20160e3491ef7eaa; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_20160e3491ef7eaa ON public.ordres_reparation USING btree (rendez_vous_id);


--
-- Name: idx_20a1e73d3f9501f; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_20a1e73d3f9501f ON public.pont_equipements USING btree (pont_id);


--
-- Name: idx_2fd8e61941defada; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_2fd8e61941defada ON public.lignes_devis USING btree (devis_id);


--
-- Name: idx_2fd8e6197bb7079b; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_2fd8e6197bb7079b ON public.lignes_devis USING btree (forfait_mo_id);


--
-- Name: idx_2fd8e619c40fcfa8; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_2fd8e619c40fcfa8 ON public.lignes_devis USING btree (piece_id);


--
-- Name: idx_303572a19eb6921; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_303572a19eb6921 ON public.calculs_tarifs USING btree (client_id);


--
-- Name: idx_303572a4a4a3511; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_303572a4a4a3511 ON public.calculs_tarifs USING btree (vehicule_id);


--
-- Name: idx_63e2418b273b5c0e; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_63e2418b273b5c0e ON public.grille_tarifaire USING btree (categorie_moto_id);


--
-- Name: idx_63e2418b9e45c554; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_63e2418b9e45c554 ON public.grille_tarifaire USING btree (prestation_id);


--
-- Name: idx_647590b19eb6921; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_647590b19eb6921 ON public.factures USING btree (client_id);


--
-- Name: idx_647590b4a4a3511; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_647590b4a4a3511 ON public.factures USING btree (vehicule_id);


--
-- Name: idx_647590b91ef7eaa; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_647590b91ef7eaa ON public.factures USING btree (rendez_vous_id);


--
-- Name: idx_65e8aa0a19eb6921; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_65e8aa0a19eb6921 ON public.rendez_vous USING btree (client_id);


--
-- Name: idx_65e8aa0a4a4a3511; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_65e8aa0a4a4a3511 ON public.rendez_vous USING btree (vehicule_id);


--
-- Name: idx_65e8aa0ad3f9501f; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_65e8aa0ad3f9501f ON public.rendez_vous USING btree (pont_id);


--
-- Name: idx_65e8aa0adcc2f5ae; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_65e8aa0adcc2f5ae ON public.rendez_vous USING btree (mecanicien_id);


--
-- Name: idx_6d0223307d35087e; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_6d0223307d35087e ON public.moto_technical_specs USING btree (modele_moto_id);


--
-- Name: idx_75ea56e016ba31db; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_75ea56e016ba31db ON public.messenger_messages USING btree (delivered_at);


--
-- Name: idx_75ea56e0e3bd61ce; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_75ea56e0e3bd61ce ON public.messenger_messages USING btree (available_at);


--
-- Name: idx_75ea56e0fb7336f0; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_75ea56e0fb7336f0 ON public.messenger_messages USING btree (queue_name);


--
-- Name: idx_78218c2d19eb6921; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_78218c2d19eb6921 ON public.vehicules USING btree (client_id);


--
-- Name: idx_78218c2dac14b70a; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_78218c2dac14b70a ON public.vehicules USING btree (modele_id);


--
-- Name: idx_78218c2dbcf5e72d; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_78218c2dbcf5e72d ON public.vehicules USING btree (categorie_id);


--
-- Name: idx_7b1b2a89670c757f; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_7b1b2a89670c757f ON public.commandes_fournisseur USING btree (fournisseur_id);


--
-- Name: idx_8b27c52b19eb6921; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_8b27c52b19eb6921 ON public.devis USING btree (client_id);


--
-- Name: idx_8b27c52b4a4a3511; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_8b27c52b4a4a3511 ON public.devis USING btree (vehicule_id);


--
-- Name: idx_957914da273b5c0e; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_957914da273b5c0e ON public.atelier_categorie_motos USING btree (categorie_moto_id);


--
-- Name: idx_9ca38ad9dcc2f5ae; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_9ca38ad9dcc2f5ae ON public.ponts USING btree (mecanicien_id);


--
-- Name: idx_a2fc7c3d91ef7eaa; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_a2fc7c3d91ef7eaa ON public.pieces_utilisees USING btree (rendez_vous_id);


--
-- Name: idx_a2fc7c3dc40fcfa8; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_a2fc7c3dc40fcfa8 ON public.pieces_utilisees USING btree (piece_id);


--
-- Name: idx_b191e5ec7f2dee08; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_b191e5ec7f2dee08 ON public.lignes_facture USING btree (facture_id);


--
-- Name: idx_c5b3af4a273b5c0e; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_c5b3af4a273b5c0e ON public.temps_interventions USING btree (categorie_moto_id);


--
-- Name: idx_c5b3af4a8ea2f8f6; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_c5b3af4a8ea2f8f6 ON public.temps_interventions USING btree (intervention_type_id);


--
-- Name: idx_de693d55670c757f; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_de693d55670c757f ON public.pieces_detachees USING btree (fournisseur_id);


--
-- Name: idx_e1afbd3791ef7eaa; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_e1afbd3791ef7eaa ON public.demandes_travaux_supp USING btree (rendez_vous_id);


--
-- Name: idx_e1b02e127f2dee08; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_e1b02e127f2dee08 ON public.paiements USING btree (facture_id);


--
-- Name: idx_e8e3b52091ef7eaa; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_e8e3b52091ef7eaa ON public.photos_intervention USING btree (rendez_vous_id);


--
-- Name: idx_eb7ce9a8273b5c0e; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_eb7ce9a8273b5c0e ON public.grille_tarifs USING btree (categorie_moto_id);


--
-- Name: idx_ec5501d182ea2e54; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_ec5501d182ea2e54 ON public.lignes_commande_fournisseur USING btree (commande_id);


--
-- Name: idx_ec5501d1c40fcfa8; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_ec5501d1c40fcfa8 ON public.lignes_commande_fournisseur USING btree (piece_id);


--
-- Name: idx_f9c0efffdcc2f5ae; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_f9c0efffdcc2f5ae ON public.absences USING btree (mecanicien_id);


--
-- Name: idx_fe18f2a319eb6921; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_fe18f2a319eb6921 ON public.rappels_email USING btree (client_id);


--
-- Name: idx_fe18f2a34cce3f86; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_fe18f2a34cce3f86 ON public.rappels_email USING btree (rdv_id);


--
-- Name: uniq_1483a5e9e7927c74; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_1483a5e9e7927c74 ON public.users USING btree (email);


--
-- Name: uniq_1483a5e9f85e0677; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_1483a5e9f85e0677 ON public.users USING btree (username);


--
-- Name: uniq_2687a01577153098; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_2687a01577153098 ON public.forfaits_mo USING btree (code);


--
-- Name: uniq_492cd9066c6e55b5; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_492cd9066c6e55b5 ON public.categorie_motos USING btree (nom);


--
-- Name: uniq_646a9dd6c53cf2ea; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_646a9dd6c53cf2ea ON public.revoked_tokens USING btree (jti);


--
-- Name: uniq_647590b38d27ab1; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_647590b38d27ab1 ON public.factures USING btree (numero_facture);


--
-- Name: uniq_65e8aa0a8d62cece; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_65e8aa0a8d62cece ON public.rendez_vous USING btree (token_suivi);


--
-- Name: uniq_7b1b2a89cffd611d; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_7b1b2a89cffd611d ON public.commandes_fournisseur USING btree (numero_commande);


--
-- Name: uniq_8b27c52b2478ee16; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_8b27c52b2478ee16 ON public.devis USING btree (numero_devis);


--
-- Name: uniq_b338d8d177153098; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_b338d8d177153098 ON public.prestations USING btree (code);


--
-- Name: uniq_b9880561989d9b62; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_b9880561989d9b62 ON public.ateliers USING btree (slug);


--
-- Name: uniq_cff3b42b91ef7eaa; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_cff3b42b91ef7eaa ON public.rapports_technicien USING btree (rendez_vous_id);


--
-- Name: uniq_de693d55aea34913; Type: INDEX; Schema: public; Owner: atelier
--

CREATE UNIQUE INDEX uniq_de693d55aea34913 ON public.pieces_detachees USING btree (reference);


--
-- Name: messenger_messages notify_trigger; Type: TRIGGER; Schema: public; Owner: atelier
--

CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON public.messenger_messages FOR EACH ROW EXECUTE FUNCTION public.notify_messenger_messages();


--
-- Name: modele_motos fk_199806c9bcf5e72d; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.modele_motos
    ADD CONSTRAINT fk_199806c9bcf5e72d FOREIGN KEY (categorie_id) REFERENCES public.categorie_motos(id);


--
-- Name: ordres_reparation fk_20160e347b8c1e64; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.ordres_reparation
    ADD CONSTRAINT fk_20160e347b8c1e64 FOREIGN KEY (demande_travaux_supp_id) REFERENCES public.demandes_travaux_supp(id);


--
-- Name: ordres_reparation fk_20160e3491ef7eaa; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.ordres_reparation
    ADD CONSTRAINT fk_20160e3491ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id);


--
-- Name: pont_equipements fk_20a1e73d3f9501f; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.pont_equipements
    ADD CONSTRAINT fk_20a1e73d3f9501f FOREIGN KEY (pont_id) REFERENCES public.ponts(id);


--
-- Name: lignes_devis fk_2fd8e61941defada; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_devis
    ADD CONSTRAINT fk_2fd8e61941defada FOREIGN KEY (devis_id) REFERENCES public.devis(id);


--
-- Name: lignes_devis fk_2fd8e6197bb7079b; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_devis
    ADD CONSTRAINT fk_2fd8e6197bb7079b FOREIGN KEY (forfait_mo_id) REFERENCES public.forfaits_mo(id);


--
-- Name: lignes_devis fk_2fd8e619c40fcfa8; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_devis
    ADD CONSTRAINT fk_2fd8e619c40fcfa8 FOREIGN KEY (piece_id) REFERENCES public.pieces_detachees(id);


--
-- Name: calculs_tarifs fk_303572a19eb6921; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.calculs_tarifs
    ADD CONSTRAINT fk_303572a19eb6921 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: calculs_tarifs fk_303572a4a4a3511; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.calculs_tarifs
    ADD CONSTRAINT fk_303572a4a4a3511 FOREIGN KEY (vehicule_id) REFERENCES public.vehicules(id);


--
-- Name: grille_tarifaire fk_63e2418b273b5c0e; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.grille_tarifaire
    ADD CONSTRAINT fk_63e2418b273b5c0e FOREIGN KEY (categorie_moto_id) REFERENCES public.categorie_motos(id);


--
-- Name: grille_tarifaire fk_63e2418b9e45c554; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.grille_tarifaire
    ADD CONSTRAINT fk_63e2418b9e45c554 FOREIGN KEY (prestation_id) REFERENCES public.prestations(id);


--
-- Name: factures fk_647590b19eb6921; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT fk_647590b19eb6921 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: factures fk_647590b4a4a3511; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT fk_647590b4a4a3511 FOREIGN KEY (vehicule_id) REFERENCES public.vehicules(id);


--
-- Name: factures fk_647590b91ef7eaa; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT fk_647590b91ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id);


--
-- Name: rendez_vous fk_65e8aa0a19eb6921; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT fk_65e8aa0a19eb6921 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: rendez_vous fk_65e8aa0a4a4a3511; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT fk_65e8aa0a4a4a3511 FOREIGN KEY (vehicule_id) REFERENCES public.vehicules(id);


--
-- Name: rendez_vous fk_65e8aa0ad3f9501f; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT fk_65e8aa0ad3f9501f FOREIGN KEY (pont_id) REFERENCES public.ponts(id);


--
-- Name: rendez_vous fk_65e8aa0adcc2f5ae; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rendez_vous
    ADD CONSTRAINT fk_65e8aa0adcc2f5ae FOREIGN KEY (mecanicien_id) REFERENCES public.mecaniciens(id);


--
-- Name: moto_technical_specs fk_6d0223307d35087e; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.moto_technical_specs
    ADD CONSTRAINT fk_6d0223307d35087e FOREIGN KEY (modele_moto_id) REFERENCES public.modele_motos(id);


--
-- Name: vehicules fk_78218c2d19eb6921; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.vehicules
    ADD CONSTRAINT fk_78218c2d19eb6921 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: vehicules fk_78218c2dac14b70a; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.vehicules
    ADD CONSTRAINT fk_78218c2dac14b70a FOREIGN KEY (modele_id) REFERENCES public.modele_motos(id);


--
-- Name: vehicules fk_78218c2dbcf5e72d; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.vehicules
    ADD CONSTRAINT fk_78218c2dbcf5e72d FOREIGN KEY (categorie_id) REFERENCES public.categorie_motos(id);


--
-- Name: commandes_fournisseur fk_7b1b2a89670c757f; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.commandes_fournisseur
    ADD CONSTRAINT fk_7b1b2a89670c757f FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseurs(id);


--
-- Name: devis fk_8b27c52b19eb6921; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.devis
    ADD CONSTRAINT fk_8b27c52b19eb6921 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: devis fk_8b27c52b4a4a3511; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.devis
    ADD CONSTRAINT fk_8b27c52b4a4a3511 FOREIGN KEY (vehicule_id) REFERENCES public.vehicules(id);


--
-- Name: atelier_categorie_motos fk_957914da273b5c0e; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.atelier_categorie_motos
    ADD CONSTRAINT fk_957914da273b5c0e FOREIGN KEY (categorie_moto_id) REFERENCES public.categorie_motos(id);


--
-- Name: ponts fk_9ca38ad9dcc2f5ae; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.ponts
    ADD CONSTRAINT fk_9ca38ad9dcc2f5ae FOREIGN KEY (mecanicien_id) REFERENCES public.mecaniciens(id);


--
-- Name: pieces_utilisees fk_a2fc7c3d91ef7eaa; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.pieces_utilisees
    ADD CONSTRAINT fk_a2fc7c3d91ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id);


--
-- Name: pieces_utilisees fk_a2fc7c3dc40fcfa8; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.pieces_utilisees
    ADD CONSTRAINT fk_a2fc7c3dc40fcfa8 FOREIGN KEY (piece_id) REFERENCES public.pieces_detachees(id);


--
-- Name: lignes_facture fk_b191e5ec7f2dee08; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_facture
    ADD CONSTRAINT fk_b191e5ec7f2dee08 FOREIGN KEY (facture_id) REFERENCES public.factures(id);


--
-- Name: temps_interventions fk_c5b3af4a273b5c0e; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.temps_interventions
    ADD CONSTRAINT fk_c5b3af4a273b5c0e FOREIGN KEY (categorie_moto_id) REFERENCES public.categorie_motos(id);


--
-- Name: temps_interventions fk_c5b3af4a8ea2f8f6; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.temps_interventions
    ADD CONSTRAINT fk_c5b3af4a8ea2f8f6 FOREIGN KEY (intervention_type_id) REFERENCES public.intervention_types(id);


--
-- Name: rapports_technicien fk_cff3b42b91ef7eaa; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rapports_technicien
    ADD CONSTRAINT fk_cff3b42b91ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id);


--
-- Name: pieces_detachees fk_de693d55670c757f; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.pieces_detachees
    ADD CONSTRAINT fk_de693d55670c757f FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseurs(id);


--
-- Name: demandes_travaux_supp fk_e1afbd3791ef7eaa; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.demandes_travaux_supp
    ADD CONSTRAINT fk_e1afbd3791ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id);


--
-- Name: paiements fk_e1b02e127f2dee08; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.paiements
    ADD CONSTRAINT fk_e1b02e127f2dee08 FOREIGN KEY (facture_id) REFERENCES public.factures(id);


--
-- Name: photos_intervention fk_e8e3b52091ef7eaa; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.photos_intervention
    ADD CONSTRAINT fk_e8e3b52091ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id);


--
-- Name: grille_tarifs fk_eb7ce9a8273b5c0e; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.grille_tarifs
    ADD CONSTRAINT fk_eb7ce9a8273b5c0e FOREIGN KEY (categorie_moto_id) REFERENCES public.categorie_motos(id);


--
-- Name: lignes_commande_fournisseur fk_ec5501d182ea2e54; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_commande_fournisseur
    ADD CONSTRAINT fk_ec5501d182ea2e54 FOREIGN KEY (commande_id) REFERENCES public.commandes_fournisseur(id);


--
-- Name: lignes_commande_fournisseur fk_ec5501d1c40fcfa8; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.lignes_commande_fournisseur
    ADD CONSTRAINT fk_ec5501d1c40fcfa8 FOREIGN KEY (piece_id) REFERENCES public.pieces_detachees(id);


--
-- Name: absences fk_f9c0efffdcc2f5ae; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.absences
    ADD CONSTRAINT fk_f9c0efffdcc2f5ae FOREIGN KEY (mecanicien_id) REFERENCES public.mecaniciens(id);


--
-- Name: rappels_email fk_fe18f2a319eb6921; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rappels_email
    ADD CONSTRAINT fk_fe18f2a319eb6921 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: rappels_email fk_fe18f2a34cce3f86; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.rappels_email
    ADD CONSTRAINT fk_fe18f2a34cce3f86 FOREIGN KEY (rdv_id) REFERENCES public.rendez_vous(id);


--
-- PostgreSQL database dump complete
--

\unrestrict gdLRzKZTo1jE9qNC4whwc2Fyg34b3yfjasAHi9zpYhr3QfYKrl8tfBbEXZQhrAO

