-- Mise à jour des clauses légales AtelierMBZ
-- Date: 2026-06-01
-- Actions: enrichissement mentions légales, CGV (mentions obligatoires facturation), pièces occasion (économie circulaire), garantie (présomption faute)

-- 1. MENTIONS LÉGALES (id=2) : ajout RM, qualification pro, TVA
UPDATE clause_legale
SET texte = E'ÉDITEUR DU SITE\nLe site Paddock est édité par l''atelier, société immatriculée au Registre du Commerce et des Sociétés (RCS) et au Répertoire des Métiers (RM) sous le numéro [SIRET], dont le siège social est situé à l''adresse de l''atelier. Numéro de TVA intracommunautaire : [TVA].\n\nDIRECTEUR DE PUBLICATION\nLe directeur de la publication est le gérant de l''atelier, titulaire d''une qualification professionnelle en mécanique automobile (CAP/BEP ou équivalent) et assurant le contrôle effectif et permanent de l''activité.\n\nHÉBERGEMENT\nLe site est hébergé par [Hébergeur], société par actions simplifiée au capital de [capital] €, immatriculée au RCS de [ville] sous le numéro [SIRET], dont le siège social est situé [adresse].\n\nPROPRIÉTÉ INTELLECTUELLE\nL''ensemble du contenu du site (textes, images, logos) est la propriété exclusive de l''atelier. Toute reproduction, représentation ou diffusion, totale ou partielle, est interdite sans autorisation préalable.\n\nCONTACT\nPour toute question relative au site, vous pouvez nous contacter à l''adresse email de l''atelier.'
WHERE id = 2;

-- 2. CGV (id=1) : ajout article 4bis sur mentions obligatoires de facturation + affichage tarifs
UPDATE clause_legale
SET texte = E'ARTICLE 1 – OBJET\nLes présentes Conditions Générales de Vente (CGV) régissent les relations contractuelles entre l''atelier et ses clients pour toute prestation de réparation, d''entretien ou de vente de pièces.\n\nARTICLE 2 – ACCEPTATION\nToute commande ou dépôt de véhicule implique l''acceptation pleine et entière des présentes CGV.\n\nARTICLE 3 – PRIX\nLes prix sont indiqués en euros TTC. L''atelier se réserve le droit de modifier ses tarifs à tout moment. Les devis acceptés par le client sont fermes et définitifs sous réserve de travaux supplémentaires non prévisibles.\n\nARTICLE 4 – PAIEMENT\nLe paiement est exigible à la restitution du véhicule ou de la marchandise. Les moyens de paiement acceptés sont : espèces, carte bancaire, virement. Aucun chèque ne sera accepté sans accord préalable.\n\nARTICLE 4 BIS – MENTIONS OBLIGATOIRES ET PÉNALITÉS\nConformément aux articles L. 441-6 et L. 441-10 du Code de commerce, toute facture émise par l''atelier comporte obligatoirement : le taux et les conditions d''escompte pour paiement anticipé (à défaut, mention « néant »), les pénalités de retard exigibles de plein droit sans rappel, calculées sur la base du taux d''intérêt légal majoré de dix (10) points, ainsi qu''une indemnité forfaitaire pour frais de recouvrement de quarante (40) euros.\n\nARTICLE 5 – AFFICHAGE DES TARIFS\nLes tarifs horaires de main-d''œuvre (T1, T2, T3) sont affichés de manière visible dans le lieu d''accueil de la clientèle et sont consultables sur simple demande.\n\nARTICLE 6 – RESPONSABILITÉ\nL''atelier est assuré pour sa responsabilité civile professionnelle. La responsabilité de l''atelier ne saurait être engagée en cas de force majeure, de vice caché préexistant ou d''utilisation anormale du véhicule.\n\nARTICLE 7 – GARANTIE\nLes pièces et main-d''œuvre sont garanties conformément aux dispositions légales en vigueur. La garantie ne couvre pas l''usure normale ni les dommages résultant d''une négligence du client.'
WHERE id = 1;

-- 3. PIÈCES D'OCCASION (id=15) : ajout obligation économie circulaire / réemploi
UPDATE clause_legale
SET texte = E'PIÈCES D''ORIGINE CONSTRUCTEUR\nPar défaut, l''atelier pose des pièces d''origine constructeur (OEM) neuves. Ces pièces bénéficient de la garantie constructeur et préservent la garantie du véhicule.\n\nPIÈCES DE QUALITÉ ÉQUIVALENTE (Q1)\nSur demande du client ou en cas d''indisponibilité des pièces OEM, l''atelier peut proposer des pièces de qualité équivalente certifiées. La garantie sur ces pièces est identique à celle des pièces OEM.\n\nPIÈCES D''OCCASION ET DE RÉEMPLOI\nConformément à l''article L. 224-67 du Code de la consommation (loi AGEC), l''atelier propose au client, lorsque cela est possible, l''utilisation de pièces issues de l''économie circulaire (pièces de réemploi ou reconditionnées). Le client reste libre d''accepter ou de refuser cette proposition. L''atelier peut également proposer des pièces d''occasion contrôlées et testées pour les véhicules anciens ou en fin de vie. Une garantie de 3 mois est appliquée sur les pièces d''occasion. Le client est informé de l''origine de la pièce avant pose.\n\nRÉCUPÉRATION DES PIÈCES USAGÉES\nLes pièces usagées remplacées appartiennent au client. Il peut les récupérer sur simple demande lors de la restitution du véhicule, dans un délai de 30 jours. Passé ce délai, l''atelier procède à leur évacuation conformément à la réglementation environnementale. Cette récupération ne s''applique pas aux pièces remplacées dans le cadre d''une garantie constructeur ou d''un échange standard.\n\nIMPACT SUR LA GARANTIE CONSTRUCTEUR\nL''utilisation de pièces non OEM ou d''occasion peut affecter la garantie constructeur restante du véhicule. L''atelier informe le client de ce risque avant tout remplacement et décline toute responsabilité en cas de refus de garantie ultérieur par le constructeur.'
WHERE id = 15;

-- 4. GARANTIE (id=5) : ajout présomption faute garagiste (jurisprudence 2022)
UPDATE clause_legale
SET texte = E'GARANTIE LÉGALE DE CONFORMITÉ\nConformément aux articles L. 217-4 et suivants du Code de la consommation, l''atelier garantit la conformité des pièces et des prestations fournies. En cas de non-conformité, le client dispose d''un délai de 2 ans à compter de la délivrance pour agir.\n\nGARANTIE DES PIÈCES\nLes pièces neuves sont garanties 12 mois à compter de leur pose, sauf mentions contraires spécifiques. Les pièces d''occasion sont garanties 3 mois. La garantie couvre les vices cachés et les défauts de fabrication.\n\nGARANTIE DES RÉPARATIONS – PRÉSOMPTION DE FAUTE\nConformément à la jurisprudence de la Cour de cassation (1re civ., 11 mai 2022, n° 20-18.867), lorsqu''un dysfonctionnement identique à celui initialement réparé survient ou persiste après l''intervention de l''atelier, la faute du professionnel et le lien causal sont présumés. Il appartient alors à l''atelier de démontrer qu''il n''a commis aucune faute.\n\nEXCLUSIONS DE GARANTIE\nSont exclus de la garantie : l''usure normale des pièces, les dommages causés par un accident, une négligence d''entretien, une modification non autorisée du véhicule, ou l''utilisation du véhicule en compétition.\n\nCONDITIONS DE PRISE EN CHARGE\nPour bénéficier de la garantie, le client doit présenter la facture d''origine et laisser le véhicule à disposition de l''atelier pour expertise. Les frais de démontage et de remontage nécessaires au diagnostic sont à la charge du client en cas de constat d''une cause exclue.'
WHERE id = 5;

-- 5. RGPD (id=3) : ajout cookies / traceurs
UPDATE clause_legale
SET texte = E'COLLECTE DES DONNÉES\nNous collectons les données personnelles nécessaires à la gestion de nos clients et de leurs véhicules : nom, prénom, adresse, email, téléphone, immatriculation, historique d''entretien.\n\nFINALITÉS\nLes données sont utilisées uniquement pour : la gestion des rendez-vous, l''établissement des devis et factures, le suivi des interventions, et l''envoi de rappels d''entretien si vous y avez consenti.\n\nBASE LÉGALE\nLe traitement est fondé sur l''exécution du contrat de réparation (article 6.1.b du RGPD) ou sur votre consentement pour les communications commerciales (article 6.1.a).\n\nCOOKIES ET TRACEURS\nLe site utilise des cookies techniques nécessaires à son fonctionnement. Aucun cookie de profilage ou de tracking publicitaire n''est déposé sans votre consentement exprès.\n\nDROITS DES PERSONNES\nVous disposez d''un droit d''accès, de rectification, d''effacement, de limitation du traitement, de portabilité et d''opposition. Pour exercer ces droits, contactez-nous par email ou courrier.\n\nDURÉE DE CONSERVATION\nLes données sont conservées pendant la durée de la relation commerciale, puis archivées conformément aux obligations légales (notamment comptables) pendant 10 ans maximum.\n\nSOUS-TRAITANTS\nNous utilisons des hébergeurs et éditeurs de logiciels qui peuvent accéder aux données. Tous nos sous-traitants sont situés dans l''UE et respectent le RGPD.'
WHERE id = 3;
