--
-- PostgreSQL database dump
--

\restrict TdF8ojDWCKtn0w1f75z6xq43zKisEUJSxP31lyLLcev6AOYZkgKZbihOwkoXdzM

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: calculs_tarifs; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.calculs_tarifs (
    id integer NOT NULL,
    prestations_ids text,
    pieces_ids text,
    total_mo_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_pieces_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ht numeric(10,2) DEFAULT 0.00 NOT NULL,
    total_ttc numeric(10,2) DEFAULT 0.00 NOT NULL,
    marge_pieces numeric(10,2) DEFAULT 0.00 NOT NULL,
    delai_total_jours integer DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_id integer,
    vehicule_id integer
);


ALTER TABLE public.calculs_tarifs OWNER TO atelier;

--
-- Name: calculs_tarifs_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.calculs_tarifs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calculs_tarifs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grille_tarifs; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.grille_tarifs (
    id integer NOT NULL,
    type_intervention character varying(100) NOT NULL,
    nom character varying(200) NOT NULL,
    description text,
    temps_minutes integer NOT NULL,
    prix_mo_ht numeric(10,2) NOT NULL,
    prix_mo_ttc numeric(10,2) NOT NULL,
    pieces_incluses boolean DEFAULT false NOT NULL,
    actif boolean DEFAULT true NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    categorie_moto_id integer
);


ALTER TABLE public.grille_tarifs OWNER TO atelier;

--
-- Name: grille_tarifs_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.grille_tarifs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grille_tarifs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: temps_interventions; Type: TABLE; Schema: public; Owner: atelier
--

CREATE TABLE public.temps_interventions (
    id integer NOT NULL,
    temps_minutes integer NOT NULL,
    coefficient_difficulte double precision DEFAULT 1 NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    categorie_moto_id integer NOT NULL,
    intervention_type_id integer NOT NULL
);


ALTER TABLE public.temps_interventions OWNER TO atelier;

--
-- Name: temps_interventions_id_seq; Type: SEQUENCE; Schema: public; Owner: atelier
--

ALTER TABLE public.temps_interventions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.temps_interventions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: calculs_tarifs; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.calculs_tarifs (id, prestations_ids, pieces_ids, total_mo_ht, total_pieces_ht, total_ht, total_ttc, marge_pieces, delai_total_jours, created_at, client_id, vehicule_id) FROM stdin;
\.


--
-- Data for Name: grille_tarifs; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.grille_tarifs (id, type_intervention, nom, description, temps_minutes, prix_mo_ht, prix_mo_ttc, pieces_incluses, actif, created_at, categorie_moto_id) FROM stdin;
\.


--
-- Data for Name: temps_interventions; Type: TABLE DATA; Schema: public; Owner: atelier
--

COPY public.temps_interventions (id, temps_minutes, coefficient_difficulte, created_at, updated_at, categorie_moto_id, intervention_type_id) FROM stdin;
\.


--
-- Name: calculs_tarifs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.calculs_tarifs_id_seq', 1, false);


--
-- Name: grille_tarifs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.grille_tarifs_id_seq', 1, false);


--
-- Name: temps_interventions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: atelier
--

SELECT pg_catalog.setval('public.temps_interventions_id_seq', 1, false);


--
-- Name: calculs_tarifs calculs_tarifs_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.calculs_tarifs
    ADD CONSTRAINT calculs_tarifs_pkey PRIMARY KEY (id);


--
-- Name: grille_tarifs grille_tarifs_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.grille_tarifs
    ADD CONSTRAINT grille_tarifs_pkey PRIMARY KEY (id);


--
-- Name: temps_interventions temps_interventions_pkey; Type: CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.temps_interventions
    ADD CONSTRAINT temps_interventions_pkey PRIMARY KEY (id);


--
-- Name: idx_303572a19eb6921; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_303572a19eb6921 ON public.calculs_tarifs USING btree (client_id);


--
-- Name: idx_303572a4a4a3511; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_303572a4a4a3511 ON public.calculs_tarifs USING btree (vehicule_id);


--
-- Name: idx_c5b3af4a273b5c0e; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_c5b3af4a273b5c0e ON public.temps_interventions USING btree (categorie_moto_id);


--
-- Name: idx_c5b3af4a8ea2f8f6; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_c5b3af4a8ea2f8f6 ON public.temps_interventions USING btree (intervention_type_id);


--
-- Name: idx_eb7ce9a8273b5c0e; Type: INDEX; Schema: public; Owner: atelier
--

CREATE INDEX idx_eb7ce9a8273b5c0e ON public.grille_tarifs USING btree (categorie_moto_id);


--
-- Name: calculs_tarifs fk_303572a19eb6921; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.calculs_tarifs
    ADD CONSTRAINT fk_303572a19eb6921 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: calculs_tarifs fk_303572a4a4a3511; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.calculs_tarifs
    ADD CONSTRAINT fk_303572a4a4a3511 FOREIGN KEY (vehicule_id) REFERENCES public.vehicules(id);


--
-- Name: temps_interventions fk_c5b3af4a273b5c0e; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.temps_interventions
    ADD CONSTRAINT fk_c5b3af4a273b5c0e FOREIGN KEY (categorie_moto_id) REFERENCES public.categorie_motos(id);


--
-- Name: temps_interventions fk_c5b3af4a8ea2f8f6; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.temps_interventions
    ADD CONSTRAINT fk_c5b3af4a8ea2f8f6 FOREIGN KEY (intervention_type_id) REFERENCES public.intervention_types(id);


--
-- Name: grille_tarifs fk_eb7ce9a8273b5c0e; Type: FK CONSTRAINT; Schema: public; Owner: atelier
--

ALTER TABLE ONLY public.grille_tarifs
    ADD CONSTRAINT fk_eb7ce9a8273b5c0e FOREIGN KEY (categorie_moto_id) REFERENCES public.categorie_motos(id);


--
-- PostgreSQL database dump complete
--

\unrestrict TdF8ojDWCKtn0w1f75z6xq43zKisEUJSxP31lyLLcev6AOYZkgKZbihOwkoXdzM

