<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417044250 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE essai_routier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, km_debut INT DEFAULT NULL, km_fin INT DEFAULT NULL, duree_minutes INT DEFAULT NULL, distance NUMERIC(6, 2) DEFAULT NULL, points_controle JSON DEFAULT NULL, anomalies TEXT DEFAULT NULL, actions_correctives TEXT DEFAULT NULL, signature_mecanicien TEXT DEFAULT NULL, realise_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, mecanicien_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, rendez_vous_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DCE2AA4691EF7EAA ON essai_routier (rendez_vous_id)');
        $this->addSql('CREATE TABLE rapport_intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, statut VARCHAR(50) NOT NULL, travaux_realises TEXT DEFAULT NULL, alertes JSON DEFAULT NULL, recommandations TEXT DEFAULT NULL, prochaine_revision_km INT DEFAULT NULL, prochaine_revision_date DATE DEFAULT NULL, kilometrage_restitution INT DEFAULT NULL, garantie TEXT DEFAULT NULL, signature_mecanicien TEXT DEFAULT NULL, signe_mecanicien_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signe_mecanicien_id INT DEFAULT NULL, signature_client TEXT DEFAULT NULL, signe_client_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signed_snapshot JSON DEFAULT NULL, signed_hash VARCHAR(64) DEFAULT NULL, signed_ip VARCHAR(45) DEFAULT NULL, motif_rectification VARCHAR(200) DEFAULT NULL, rectified_by INT DEFAULT NULL, rectified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rendez_vous_id INT NOT NULL, rectified_from_id INT DEFAULT NULL, essai_routier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EE7B38A08AA53C ON rapport_intervention (rectified_from_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_75EE7B388BAE3A9 ON rapport_intervention (essai_routier_id)');
        $this->addSql('CREATE INDEX idx_rapport_rdv ON rapport_intervention (rendez_vous_id)');
        $this->addSql('ALTER TABLE essai_routier ADD CONSTRAINT FK_DCE2AA4691EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rapport_intervention ADD CONSTRAINT FK_75EE7B3891EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rapport_intervention ADD CONSTRAINT FK_75EE7B38A08AA53C FOREIGN KEY (rectified_from_id) REFERENCES rapport_intervention (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rapport_intervention ADD CONSTRAINT FK_75EE7B388BAE3A9 FOREIGN KEY (essai_routier_id) REFERENCES essai_routier (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE essai_routier DROP CONSTRAINT FK_DCE2AA4691EF7EAA');
        $this->addSql('ALTER TABLE rapport_intervention DROP CONSTRAINT FK_75EE7B3891EF7EAA');
        $this->addSql('ALTER TABLE rapport_intervention DROP CONSTRAINT FK_75EE7B38A08AA53C');
        $this->addSql('ALTER TABLE rapport_intervention DROP CONSTRAINT FK_75EE7B388BAE3A9');
        $this->addSql('DROP TABLE essai_routier');
        $this->addSql('DROP TABLE rapport_intervention');
    }
}
