<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522160837 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Drop FK constraints first (PostgreSQL requires this before dropping referenced tables)
        $this->addSql('ALTER TABLE lignes_devis DROP CONSTRAINT IF EXISTS fk_2fd8e6197bb7079b');
        $this->addSql('ALTER TABLE rapport_intervention DROP CONSTRAINT IF EXISTS fk_75ee7b388bae3a9');
        $this->addSql('ALTER TABLE rapport_intervention DROP CONSTRAINT IF EXISTS fk_75ee7b3891ef7eaa');
        $this->addSql('ALTER TABLE rapport_intervention DROP CONSTRAINT IF EXISTS fk_75ee7b38a08aa53c');
        $this->addSql('ALTER TABLE rapports_technicien DROP CONSTRAINT IF EXISTS fk_cff3b42b91ef7eaa');

        // Drop index and column on lignes_devis
        $this->addSql('DROP INDEX IF EXISTS idx_2fd8e6197bb7079b');
        $this->addSql('ALTER TABLE lignes_devis DROP IF EXISTS forfait_mo_id');

        // Drop obsolete tables
        $this->addSql('DROP TABLE IF EXISTS forfaits_mo');
        $this->addSql('DROP TABLE IF EXISTS intervention_types');
        $this->addSql('DROP TABLE IF EXISTS rapport_intervention');
        $this->addSql('DROP TABLE IF EXISTS rapports_technicien');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE forfaits_mo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, nom VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, categorie VARCHAR(100) DEFAULT NULL, temps_base_minutes INT NOT NULL, taux_horaire_applique VARCHAR(50) DEFAULT \'standard\' NOT NULL, prix_forfait_mo_ht NUMERIC(10, 2) NOT NULL, prix_forfait_mo_ttc NUMERIC(10, 2) NOT NULL, inclut_pieces INT DEFAULT 0 NOT NULL, description_pieces_incluses TEXT DEFAULT NULL, prix_pieces_incluses_ht NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, type_vehicule VARCHAR(50) DEFAULT \'tous\' NOT NULL, cylindree_min INT DEFAULT NULL, cylindree_max INT DEFAULT NULL, is_active INT DEFAULT 1 NOT NULL, is_promo INT DEFAULT 0 NOT NULL, prix_promo_mo_ttc NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_2687a01577153098 ON forfaits_mo (code)');
        $this->addSql('CREATE TABLE intervention_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, prix_base NUMERIC(10, 2) NOT NULL, temps_estime INT NOT NULL, is_active INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rapport_intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, statut VARCHAR(50) NOT NULL, travaux_realises TEXT DEFAULT NULL, alertes JSON DEFAULT NULL, recommandations TEXT DEFAULT NULL, prochaine_revision_km INT DEFAULT NULL, prochaine_revision_date DATE DEFAULT NULL, kilometrage_restitution INT DEFAULT NULL, garantie TEXT DEFAULT NULL, signature_mecanicien TEXT DEFAULT NULL, signe_mecanicien_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signe_mecanicien_id INT DEFAULT NULL, signature_client TEXT DEFAULT NULL, signe_client_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signed_snapshot JSON DEFAULT NULL, signed_hash VARCHAR(64) DEFAULT NULL, signed_ip VARCHAR(45) DEFAULT NULL, motif_rectification VARCHAR(200) DEFAULT NULL, rectified_by INT DEFAULT NULL, rectified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rendez_vous_id INT NOT NULL, rectified_from_id INT DEFAULT NULL, essai_routier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rapport_rdv ON rapport_intervention (rendez_vous_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_75ee7b388bae3a9 ON rapport_intervention (essai_routier_id)');
        $this->addSql('CREATE INDEX idx_75ee7b38a08aa53c ON rapport_intervention (rectified_from_id)');
        $this->addSql('CREATE TABLE rapports_technicien (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, points_controle TEXT DEFAULT \'{}\' NOT NULL, alertes TEXT DEFAULT NULL, recommandations TEXT DEFAULT NULL, travaux_realises TEXT DEFAULT NULL, pieces_utilisees TEXT DEFAULT \'[]\' NOT NULL, statut VARCHAR(50) DEFAULT \'en_cours\' NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rendez_vous_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cff3b42b91ef7eaa ON rapports_technicien (rendez_vous_id)');
        $this->addSql('ALTER TABLE rapport_intervention ADD CONSTRAINT fk_75ee7b388bae3a9 FOREIGN KEY (essai_routier_id) REFERENCES essai_routier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rapport_intervention ADD CONSTRAINT fk_75ee7b3891ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rapport_intervention ADD CONSTRAINT fk_75ee7b38a08aa53c FOREIGN KEY (rectified_from_id) REFERENCES rapport_intervention (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rapports_technicien ADD CONSTRAINT fk_cff3b42b91ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lignes_devis ADD forfait_mo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lignes_devis ADD CONSTRAINT fk_2fd8e6197bb7079b FOREIGN KEY (forfait_mo_id) REFERENCES forfaits_mo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_2fd8e6197bb7079b ON lignes_devis (forfait_mo_id)');
    }
}
