<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416171207 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE vehicules ALTER controle_technique_resultat TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER prix_vente_souhaite DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER commission_valeur DROP DEFAULT');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_502B9DCF4A4A3511 ON vo_depot_ventes (vehicule_id)');
        $this->addSql('ALTER TABLE vo_documents ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_documents ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE vo_documents ALTER retention_years DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_factures ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_factures ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX vo_factures_numero_facture_key RENAME TO UNIQ_93727E6438D27AB1');
        $this->addSql('ALTER TABLE vo_livre_police ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_livre_police ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3C2D8CE19A724477 ON vo_livre_police (vo_purchase_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3C2D8CE14CB2AC87 ON vo_livre_police (vo_depot_vente_id)');
        $this->addSql('ALTER TABLE vo_purchases ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_purchases ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE vo_purchases ALTER purchase_price DROP DEFAULT');
        $this->addSql('ALTER TABLE vo_purchases ALTER target_sale_price DROP DEFAULT');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_77FC78104A4A3511 ON vo_purchases (vehicule_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vehicules ALTER controle_technique_resultat TYPE VARCHAR(30)');
        $this->addSql('DROP INDEX UNIQ_502B9DCF4A4A3511');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER id SET DEFAULT nextval(\'vo_depot_ventes_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER prix_vente_souhaite SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE vo_depot_ventes ALTER commission_valeur SET DEFAULT \'0\'');
        $this->addSql('CREATE INDEX IDX_502B9DCF4A4A3511 ON vo_depot_ventes (vehicule_id)');
        $this->addSql('ALTER TABLE vo_documents ALTER id SET DEFAULT nextval(\'vo_documents_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE vo_documents ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE vo_documents ALTER retention_years SET DEFAULT 5');
        $this->addSql('ALTER TABLE vo_factures ALTER id SET DEFAULT nextval(\'vo_factures_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE vo_factures ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_93727e6438d27ab1 RENAME TO vo_factures_numero_facture_key');
        $this->addSql('DROP INDEX UNIQ_3C2D8CE19A724477');
        $this->addSql('DROP INDEX UNIQ_3C2D8CE14CB2AC87');
        $this->addSql('ALTER TABLE vo_livre_police ALTER id SET DEFAULT nextval(\'vo_livre_police_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE vo_livre_police ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX IDX_3C2D8CE14CB2AC87 ON vo_livre_police (vo_depot_vente_id)');
        $this->addSql('CREATE INDEX IDX_3C2D8CE19A724477 ON vo_livre_police (vo_purchase_id)');
        $this->addSql('DROP INDEX UNIQ_77FC78104A4A3511');
        $this->addSql('ALTER TABLE vo_purchases ALTER id SET DEFAULT nextval(\'vo_purchases_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE vo_purchases ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE vo_purchases ALTER purchase_price SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE vo_purchases ALTER target_sale_price SET DEFAULT \'0\'');
        $this->addSql('CREATE INDEX IDX_77FC78104A4A3511 ON vo_purchases (vehicule_id)');
    }
}
