<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417041023 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT NOT NULL, channel VARCHAR(20) NOT NULL, provider VARCHAR(50) NOT NULL, template_code VARCHAR(100) DEFAULT NULL, to_recipient VARCHAR(255) NOT NULL, subject VARCHAR(500) DEFAULT NULL, status VARCHAR(30) NOT NULL, provider_message_id VARCHAR(255) DEFAULT NULL, error_message TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, related_entity_type VARCHAR(100) DEFAULT NULL, related_entity_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_notiflog_atelier_date ON notification_logs (atelier_id, sent_at)');
        $this->addSql('CREATE INDEX idx_notiflog_status ON notification_logs (status)');
        $this->addSql('CREATE INDEX idx_notiflog_entity ON notification_logs (related_entity_type, related_entity_id)');
        $this->addSql('CREATE TABLE notification_provider_configs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT NOT NULL, channel VARCHAR(20) NOT NULL, provider VARCHAR(50) NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, is_fallback BOOLEAN DEFAULT false NOT NULL, priority INT DEFAULT 1 NOT NULL, config_encrypted TEXT NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, last_test_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_test_success BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_atelier_channel ON notification_provider_configs (atelier_id, channel, provider)');
        $this->addSql('CREATE TABLE notification_templates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT NOT NULL, code VARCHAR(100) NOT NULL, channel VARCHAR(20) NOT NULL, libelle VARCHAR(200) NOT NULL, sujet VARCHAR(500) DEFAULT NULL, corps TEXT NOT NULL, variables JSON NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_template_atelier_code_channel ON notification_templates (atelier_id, code, channel)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE notification_logs');
        $this->addSql('DROP TABLE notification_provider_configs');
        $this->addSql('DROP TABLE notification_templates');
    }
}
