<?php
declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260703100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Lot B — table etat_des_lieux (check-in au dépôt, document gelé) + config_atelier.checkin_obligatoire';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE etat_des_lieux (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                rendez_vous_id INT NOT NULL,
                atelier_id INT DEFAULT NULL,
                kilometrage INT DEFAULT NULL,
                niveau_carburant VARCHAR(20) DEFAULT NULL,
                observations TEXT DEFAULT NULL,
                etat_vehicule JSON DEFAULT NULL,
                signature_client TEXT DEFAULT NULL,
                signed_by_nom VARCHAR(200) DEFAULT NULL,
                signed_by_user_id INT DEFAULT NULL,
                signed_snapshot JSON DEFAULT NULL,
                signed_hash VARCHAR(64) DEFAULT NULL,
                signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                signed_ip VARCHAR(45) DEFAULT NULL,
                signed_user_agent VARCHAR(500) DEFAULT NULL,
                pdf_filename VARCHAR(100) DEFAULT NULL,
                snap_client_nom VARCHAR(200) DEFAULT NULL,
                snap_client_prenom VARCHAR(200) DEFAULT NULL,
                snap_vehicule_plaque VARCHAR(20) DEFAULT NULL,
                snap_vehicule_marque VARCHAR(100) DEFAULT NULL,
                snap_vehicule_modele VARCHAR(100) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                CONSTRAINT fk_etat_des_lieux_rdv FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_etat_des_lieux_rdv ON etat_des_lieux (rendez_vous_id)');
        $this->addSql('CREATE INDEX idx_etat_des_lieux_atelier ON etat_des_lieux (atelier_id)');
        $this->addSql('ALTER TABLE config_atelier ADD checkin_obligatoire BOOLEAN NOT NULL DEFAULT TRUE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE config_atelier DROP checkin_obligatoire');
        $this->addSql('DROP TABLE IF EXISTS etat_des_lieux');
    }
}
