<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518142941 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rdv_commandes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, rdv_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rdv_commande_rdv ON rdv_commandes (rdv_id)');
        $this->addSql('ALTER TABLE rdv_commandes ADD CONSTRAINT FK_73DDA1CD4CCE3F86 FOREIGN KEY (rdv_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rdv_commandes DROP CONSTRAINT FK_73DDA1CD4CCE3F86');
        $this->addSql('DROP TABLE rdv_commandes');
    }
}
