<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417044805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE commande_piece (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, reference VARCHAR(100) NOT NULL, designation VARCHAR(255) NOT NULL, quantite INT DEFAULT 1 NOT NULL, fournisseur VARCHAR(200) DEFAULT NULL, numero_commande_fournisseur VARCHAR(100) DEFAULT NULL, prix_achat NUMERIC(10, 2) DEFAULT NULL, prix_vente NUMERIC(10, 2) DEFAULT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_livraison_estimee DATE DEFAULT NULL, date_livraison_reelle DATE DEFAULT NULL, statut VARCHAR(30) DEFAULT \'a_commander\' NOT NULL, notes TEXT DEFAULT NULL, client_notifie_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notified_by INT DEFAULT NULL, rendez_vous_id INT NOT NULL, ordre_reparation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7DA2D4E091EF7EAA ON commande_piece (rendez_vous_id)');
        $this->addSql('CREATE INDEX IDX_7DA2D4E060A72AD6 ON commande_piece (ordre_reparation_id)');
        $this->addSql('CREATE INDEX idx_commande_piece_rdv_statut ON commande_piece (rendez_vous_id, statut)');
        $this->addSql('ALTER TABLE commande_piece ADD CONSTRAINT FK_7DA2D4E091EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande_piece ADD CONSTRAINT FK_7DA2D4E060A72AD6 FOREIGN KEY (ordre_reparation_id) REFERENCES ordres_reparation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE config_atelier ADD delai_relance1_jours_ouvres INT DEFAULT 15 NOT NULL');
        $this->addSql('ALTER TABLE config_atelier ADD delai_relance2_jours_ouvres INT DEFAULT 30 NOT NULL');
        $this->addSql('ALTER TABLE config_atelier ADD delai_propose_gardiennage_jours_ouvres INT DEFAULT 45 NOT NULL');
        $this->addSql('ALTER TABLE config_atelier ADD delai_procedure_abandon_jours_ouvres INT DEFAULT 180 NOT NULL');
        $this->addSql('ALTER TABLE config_atelier ADD tarif_gardiennage_journalier NUMERIC(10, 2) DEFAULT \'5.00\' NOT NULL');
        $this->addSql('ALTER TABLE config_atelier ADD garantie_travaux_jours INT DEFAULT 30 NOT NULL');
        $this->addSql('ALTER TABLE config_atelier ADD jours_fermeture_hebdo JSON DEFAULT \'["sunday"]\' NOT NULL');
        $this->addSql('ALTER TABLE config_atelier ADD dates_fermeture_exceptionnelles JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD emplacement_stockage VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD photo_stockage_filename VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD mis_en_stockage_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD mis_en_stockage_par INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD gardiennage_debut_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD gardiennage_debut_par INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rendez_vous ADD gardiennage_motif TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande_piece DROP CONSTRAINT FK_7DA2D4E091EF7EAA');
        $this->addSql('ALTER TABLE commande_piece DROP CONSTRAINT FK_7DA2D4E060A72AD6');
        $this->addSql('DROP TABLE commande_piece');
        $this->addSql('ALTER TABLE config_atelier DROP delai_relance1_jours_ouvres');
        $this->addSql('ALTER TABLE config_atelier DROP delai_relance2_jours_ouvres');
        $this->addSql('ALTER TABLE config_atelier DROP delai_propose_gardiennage_jours_ouvres');
        $this->addSql('ALTER TABLE config_atelier DROP delai_procedure_abandon_jours_ouvres');
        $this->addSql('ALTER TABLE config_atelier DROP tarif_gardiennage_journalier');
        $this->addSql('ALTER TABLE config_atelier DROP garantie_travaux_jours');
        $this->addSql('ALTER TABLE config_atelier DROP jours_fermeture_hebdo');
        $this->addSql('ALTER TABLE config_atelier DROP dates_fermeture_exceptionnelles');
        $this->addSql('ALTER TABLE rendez_vous DROP emplacement_stockage');
        $this->addSql('ALTER TABLE rendez_vous DROP photo_stockage_filename');
        $this->addSql('ALTER TABLE rendez_vous DROP mis_en_stockage_at');
        $this->addSql('ALTER TABLE rendez_vous DROP mis_en_stockage_par');
        $this->addSql('ALTER TABLE rendez_vous DROP gardiennage_debut_at');
        $this->addSql('ALTER TABLE rendez_vous DROP gardiennage_debut_par');
        $this->addSql('ALTER TABLE rendez_vous DROP gardiennage_motif');
    }
}
