<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417043854 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE annulation_rdv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, motif VARCHAR(50) NOT NULL, commentaire TEXT DEFAULT NULL, annule_par INT DEFAULT NULL, annule_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_rdv_original TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut_avant_annulation VARCHAR(50) DEFAULT NULL, rendez_vous_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_annulation_rdv ON annulation_rdv (rendez_vous_id)');
        $this->addSql('ALTER TABLE annulation_rdv ADD CONSTRAINT FK_6FD1CA5791EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE annulation_rdv DROP CONSTRAINT FK_6FD1CA5791EF7EAA');
        $this->addSql('DROP TABLE annulation_rdv');
    }
}
