<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260417100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'LOT 6: Create roles_metier, role_permission_entries, modules tables + seed 6 role templates';
    }

    public function up(Schema $schema): void
    {
        // modules reference table
        $this->addSql('CREATE TABLE modules (
            code VARCHAR(50) NOT NULL,
            libelle VARCHAR(120) NOT NULL,
            actions JSON NOT NULL,
            PRIMARY KEY(code)
        )');

        // roles_metier table
        $this->addSql('CREATE TABLE roles_metier (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            atelier_id INT DEFAULT NULL,
            code VARCHAR(50) NOT NULL,
            libelle VARCHAR(120) NOT NULL,
            description TEXT DEFAULT NULL,
            base_role VARCHAR(30) NOT NULL DEFAULT \'ROLE_USER\',
            herite_de_id INT DEFAULT NULL,
            is_system_template BOOLEAN NOT NULL DEFAULT false,
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by INT DEFAULT NULL,
            PRIMARY KEY(id),
            CONSTRAINT fk_roles_metier_herite FOREIGN KEY (herite_de_id) REFERENCES roles_metier (id) ON DELETE SET NULL
        )');
        $this->addSql('CREATE UNIQUE INDEX uq_roles_metier_atelier_code ON roles_metier (atelier_id, code)');

        // role_permission_entries table
        $this->addSql('CREATE TABLE role_permission_entries (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            role_metier_id INT NOT NULL,
            module VARCHAR(50) NOT NULL,
            action VARCHAR(30) NOT NULL,
            scope VARCHAR(30) NOT NULL DEFAULT \'atelier\',
            conditions JSON DEFAULT NULL,
            granted BOOLEAN NOT NULL DEFAULT true,
            PRIMARY KEY(id),
            CONSTRAINT fk_rpe_role_metier FOREIGN KEY (role_metier_id) REFERENCES roles_metier (id) ON DELETE CASCADE
        )');
        $this->addSql('CREATE UNIQUE INDEX uq_rpe_role_module_action ON role_permission_entries (role_metier_id, module, action)');

        // Add role_metier_id to users
        $this->addSql('ALTER TABLE users ADD role_metier_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT fk_users_role_metier FOREIGN KEY (role_metier_id) REFERENCES roles_metier (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX idx_users_role_metier ON users (role_metier_id)');

        // Seed modules
        $this->seedModules();

        // Seed 6 role templates
        $this->seedRoleTemplates();
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_role_metier');
        $this->addSql('DROP INDEX IF EXISTS idx_users_role_metier');
        $this->addSql('ALTER TABLE users DROP COLUMN IF EXISTS role_metier_id');
        $this->addSql('DROP TABLE IF EXISTS role_permission_entries');
        $this->addSql('DROP TABLE IF EXISTS roles_metier');
        $this->addSql('DROP TABLE IF EXISTS modules');
    }

    private function seedModules(): void
    {
        $modules = [
            ['dashboard',    'Tableau de bord',      '["view"]'],
            ['rdv',          'Rendez-vous',          '["view","create","edit","delete","export"]'],
            ['planning',     'Planning',             '["view"]'],
            ['workshop',     'Atelier',              '["view"]'],
            ['suivi',        'Suivi client',         '["view"]'],
            ['clients',      'Clients',              '["view","create","edit","delete","export"]'],
            ['or',           'Ordres de réparation', '["view","create","edit","delete","export"]'],
            ['motos',        'Véhicules / Motos',    '["view","create","edit","delete"]'],
            ['devis',        'Devis',                '["view","create","edit","delete","export"]'],
            ['facturation',  'Facturation',          '["view","create","edit","delete","export"]'],
            ['stock',        'Stock / Pièces',       '["view","create","edit","delete","export"]'],
            ['tarifs',       'Tarifs / Catalogue',   '["view","create","edit","delete"]'],
            ['vo',           'Véhicules Occasion',   '["view","create","edit","delete","export"]'],
            ['absences',     'Absences',             '["view","create","edit","delete"]'],
            ['admin',        'Administration',       '["view","create","edit","delete"]'],
            ['demande_travaux_supp', 'Demande travaux supp.', '["view","create","edit","delete"]'],
        ];

        foreach ($modules as [$code, $libelle, $actions]) {
            $this->addSql("INSERT INTO modules (code, libelle, actions) VALUES (?, ?, ?)", [$code, $libelle, $actions]);
        }
    }

    private function seedRoleTemplates(): void
    {
        // 1. Responsable Atelier (ROLE_ADMIN) — full workshop access
        $this->addSql("INSERT INTO roles_metier (code, libelle, description, base_role, is_system_template) VALUES ('responsable_atelier', 'Responsable Atelier', 'Accès complet aux opérations atelier', 'ROLE_ADMIN', true)");
        $this->seedPermissions('responsable_atelier', [
            ['dashboard', 'view'], ['rdv', 'view'], ['rdv', 'create'], ['rdv', 'edit'], ['rdv', 'delete'], ['rdv', 'export'],
            ['planning', 'view'], ['workshop', 'view'], ['suivi', 'view'],
            ['clients', 'view'], ['clients', 'create'], ['clients', 'edit'], ['clients', 'delete'], ['clients', 'export'],
            ['or', 'view'], ['or', 'create'], ['or', 'edit'], ['or', 'delete'], ['or', 'export'],
            ['motos', 'view'], ['motos', 'create'], ['motos', 'edit'], ['motos', 'delete'],
            ['devis', 'view'], ['devis', 'create'], ['devis', 'edit'], ['devis', 'delete'], ['devis', 'export'],
            ['facturation', 'view'], ['facturation', 'create'], ['facturation', 'edit'], ['facturation', 'delete'], ['facturation', 'export'],
            ['stock', 'view'], ['stock', 'create'], ['stock', 'edit'], ['stock', 'delete'], ['stock', 'export'],
            ['tarifs', 'view'], ['tarifs', 'create'], ['tarifs', 'edit'], ['tarifs', 'delete'],
            ['absences', 'view'], ['absences', 'create'], ['absences', 'edit'], ['absences', 'delete'],
            ['admin', 'view'], ['admin', 'create'], ['admin', 'edit'], ['admin', 'delete'],
            ['demande_travaux_supp', 'view'], ['demande_travaux_supp', 'create'], ['demande_travaux_supp', 'edit'], ['demande_travaux_supp', 'delete'],
        ]);

        // 2. Responsable Magasin (ROLE_ADMIN) — stock/parts focus
        $this->addSql("INSERT INTO roles_metier (code, libelle, description, base_role, is_system_template) VALUES ('responsable_magasin', 'Responsable Magasin', 'Gestion stock et approvisionnement', 'ROLE_ADMIN', true)");
        $this->seedPermissions('responsable_magasin', [
            ['dashboard', 'view'],
            ['stock', 'view'], ['stock', 'create'], ['stock', 'edit'], ['stock', 'delete'], ['stock', 'export'],
            ['tarifs', 'view'], ['tarifs', 'create'], ['tarifs', 'edit'], ['tarifs', 'delete'],
            ['clients', 'view'], ['clients', 'create'], ['clients', 'edit'],
            ['motos', 'view'],
            ['or', 'view'],
            ['facturation', 'view'],
            ['demande_travaux_supp', 'view'],
        ]);

        // 3. Réceptionniste (ROLE_USER) — customer-facing
        $this->addSql("INSERT INTO roles_metier (code, libelle, description, base_role, is_system_template) VALUES ('receptionniste', 'Réceptionniste', 'Accueil client, prise de RDV et devis', 'ROLE_USER', true)");
        $this->seedPermissions('receptionniste', [
            ['dashboard', 'view'],
            ['rdv', 'view'], ['rdv', 'create'], ['rdv', 'edit'],
            ['planning', 'view'], ['suivi', 'view'],
            ['clients', 'view'], ['clients', 'create'], ['clients', 'edit'],
            ['motos', 'view'], ['motos', 'create'], ['motos', 'edit'],
            ['devis', 'view'], ['devis', 'create'],
            ['or', 'view'],
            ['demande_travaux_supp', 'view'],
        ]);

        // 4. Mécanicien (ROLE_USER) — workshop only, NO price/time, NO edit on OR/Devis/Facture
        $this->addSql("INSERT INTO roles_metier (code, libelle, description, base_role, is_system_template) VALUES ('mecanicien', 'Mécanicien', 'Travail atelier uniquement — aucun accès prix/temps', 'ROLE_USER', true)");
        $this->seedPermissions('mecanicien', [
            ['planning', 'view'],
            ['workshop', 'view'],
            ['or', 'view'],
            ['motos', 'view'],
            ['stock', 'view'],
            ['tarifs', 'view'], // catalogue only, no price fields
            ['demande_travaux_supp', 'create'], // can request additional work
            ['demande_travaux_supp', 'view'],
        ], 'own');

        // 5. Comptable (ROLE_USER) — financial
        $this->addSql("INSERT INTO roles_metier (code, libelle, description, base_role, is_system_template) VALUES ('comptable', 'Comptable', 'Gestion financière et facturation', 'ROLE_USER', true)");
        $this->seedPermissions('comptable', [
            ['dashboard', 'view'],
            ['facturation', 'view'], ['facturation', 'create'], ['facturation', 'edit'], ['facturation', 'delete'], ['facturation', 'export'],
            ['devis', 'view'], ['devis', 'create'], ['devis', 'edit'], ['devis', 'export'],
            ['clients', 'view'],
            ['or', 'view'],
            ['tarifs', 'view'],
        ]);

        // 6. VO Manager (ROLE_USER) — vehicle sales
        $this->addSql("INSERT INTO roles_metier (code, libelle, description, base_role, is_system_template) VALUES ('vo_manager', 'VO Manager', 'Gestion véhicules d''occasion', 'ROLE_USER', true)");
        $this->seedPermissions('vo_manager', [
            ['dashboard', 'view'],
            ['vo', 'view'], ['vo', 'create'], ['vo', 'edit'], ['vo', 'delete'], ['vo', 'export'],
            ['motos', 'view'], ['motos', 'create'], ['motos', 'edit'],
            ['clients', 'view'], ['clients', 'create'], ['clients', 'edit'],
            ['facturation', 'view'],
        ]);
    }

    private function seedPermissions(string $roleCode, array $perms, string $defaultScope = 'atelier'): void
    {
        foreach ($perms as [$module, $action]) {
            $scope = $defaultScope;
            // Mécanicien-specific: demande_travaux_supp.create is 'own' scope
            if ($roleCode === 'mecanicien' && $module === 'demande_travaux_supp' && $action === 'create') {
                $scope = 'own';
            } elseif ($roleCode !== 'mecanicien') {
                $scope = 'atelier';
            }
            $this->addSql(
                "INSERT INTO role_permission_entries (role_metier_id, module, action, scope) 
                 SELECT id, ?, ?, ? FROM roles_metier WHERE code = ? AND atelier_id IS NULL",
                [$module, $action, $scope, $roleCode]
            );
        }
    }
}
