<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612155318 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rdv_statut_historique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, transition VARCHAR(100) NOT NULL, statut VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, rendez_vous_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A3CAE1A91EF7EAA ON rdv_statut_historique (rendez_vous_id)');
        $this->addSql('CREATE INDEX idx_rdv_statut_histo_rdv ON rdv_statut_historique (rendez_vous_id, created_at)');
        $this->addSql('ALTER TABLE rdv_statut_historique ADD CONSTRAINT FK_3A3CAE1A91EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE config_atelier ADD notifications_etapes JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE demandes_travaux_supp ADD sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE demandes_travaux_supp ADD relance_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rdv_statut_historique DROP CONSTRAINT FK_3A3CAE1A91EF7EAA');
        $this->addSql('DROP TABLE rdv_statut_historique');
        $this->addSql('ALTER TABLE config_atelier DROP notifications_etapes');
        $this->addSql('ALTER TABLE demandes_travaux_supp DROP sent_at');
        $this->addSql('ALTER TABLE demandes_travaux_supp DROP relance_at');
    }
}
