<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417045135 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE clause_legale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(200) NOT NULL, texte TEXT NOT NULL, version INT DEFAULT 1 NOT NULL, effective_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_clause_active ON clause_legale (atelier_id, code, is_active)');
        $this->addSql('CREATE UNIQUE INDEX uq_clause_code_version ON clause_legale (atelier_id, code, version)');

        // Seed default legal clauses
        $now = date('Y-m-d H:i:s');
        $this->addSql("INSERT INTO clause_legale (code, libelle, texte, version, effective_from, is_active, created_at) VALUES
            ('accessoires', 'Clause accessoires et effets personnels', 'L''atelier décline toute responsabilité concernant les effets personnels et accessoires laissés dans, sur ou avec le véhicule (casque, gants, blouson, antivol, GPS, bagages, etc.). Il est expressément recommandé au client de récupérer tous ses effets avant de laisser son véhicule. Le client reconnaît avoir été informé de cette clause et décharge l''atelier de toute responsabilité en cas de perte, vol ou dégradation desdits accessoires. La présente clause ne s''applique pas en cas de faute lourde ou intentionnelle de l''atelier ou de ses préposés.', 1, '$now', true, '$now'),
            ('essai', 'Clause essai routier', 'Un essai routier systématique est effectué par le mécanicien intervenant avant restitution du véhicule, conformément aux règles de l''art et à l''obligation de résultat de l''atelier. Le client reconnaît avoir été informé de cette pratique et y consent.', 1, '$now', true, '$now'),
            ('garantie', 'Clause garantie travaux', 'Les travaux réalisés par l''atelier sont garantis pendant 30 jours à compter de la date de restitution, hors pièces d''usure (plaquettes, pneus, huiles, filtres) et dégâts d''usage. La garantie couvre la reprise gratuite des travaux en cas de malfaçon avérée. Elle est annulée en cas d''intervention extérieure sur les mêmes organes.', 1, '$now', true, '$now'),
            ('gardiennage', 'Clause gardiennage', 'À défaut de reprise du véhicule dans un délai de 45 jours ouvrés après notification de disponibilité, des frais de gardiennage pourront être appliqués à raison de 5€ par jour ouvré, après relance préalable. À défaut de reprise dans un délai de 180 jours ouvrés, une procédure de véhicule abandonné pourra être engagée conformément au Code de commerce.', 1, '$now', true, '$now'),
            ('cgv', 'Conditions générales de vente', 'Les présentes conditions générales de vente régissent les relations entre l''atelier et le client. Tout devis accepté ou ordre de réparation signé vaut acceptation des présentes CGV. Les travaux sont facturés selon les tarifs en vigueur au jour de la commande.', 1, '$now', true, '$now')
        ");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE clause_legale');
    }
}
