<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260605110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create mouvements_stock table for immutable stock audit trail';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mouvements_stock (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            atelier_id INT DEFAULT NULL,
            piece_id INT NOT NULL,
            type VARCHAR(20) NOT NULL,
            quantite INT NOT NULL,
            prix_unitaire_ht NUMERIC(10, 2) DEFAULT NULL,
            motif VARCHAR(500) DEFAULT NULL,
            commande_fournisseur_id INT DEFAULT NULL,
            rendez_vous_id INT DEFAULT NULL,
            utilisateur_id INT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE INDEX IDX_MS_PIECE ON mouvements_stock (piece_id)');
        $this->addSql('CREATE INDEX IDX_MS_COMMANDE ON mouvements_stock (commande_fournisseur_id)');
        $this->addSql('CREATE INDEX IDX_MS_RDV ON mouvements_stock (rendez_vous_id)');
        $this->addSql('CREATE INDEX IDX_MS_USER ON mouvements_stock (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_MS_ATELIER ON mouvements_stock (atelier_id)');
        $this->addSql('CREATE INDEX IDX_MS_CREATED ON mouvements_stock (created_at)');

        $this->addSql('ALTER TABLE mouvements_stock ADD CONSTRAINT FK_MS_PIECE FOREIGN KEY (piece_id) REFERENCES pieces_detachees (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mouvements_stock ADD CONSTRAINT FK_MS_COMMANDE FOREIGN KEY (commande_fournisseur_id) REFERENCES commandes_fournisseur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mouvements_stock ADD CONSTRAINT FK_MS_RDV FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mouvements_stock ADD CONSTRAINT FK_MS_USER FOREIGN KEY (utilisateur_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mouvements_stock DROP CONSTRAINT FK_MS_PIECE');
        $this->addSql('ALTER TABLE mouvements_stock DROP CONSTRAINT FK_MS_COMMANDE');
        $this->addSql('ALTER TABLE mouvements_stock DROP CONSTRAINT FK_MS_RDV');
        $this->addSql('ALTER TABLE mouvements_stock DROP CONSTRAINT FK_MS_USER');
        $this->addSql('DROP TABLE mouvements_stock');
    }
}
