<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520150852 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analytics_alert_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT NOT NULL, name VARCHAR(100) NOT NULL, metric VARCHAR(50) NOT NULL, operator VARCHAR(10) NOT NULL, threshold_value NUMERIC(12, 2) DEFAULT \'0.00\' NOT NULL, severity VARCHAR(20) DEFAULT \'warning\' NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, cooldown_minutes INT DEFAULT 60 NOT NULL, last_triggered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_alert_rule_atelier_active ON analytics_alert_rules (atelier_id, is_active)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE analytics_alert_rules');
    }
}
