<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620000002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_client_facts (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              atelier_id INT NOT NULL,
              client_id INT NOT NULL,
              periode_annee INT NOT NULL,
              periode_mois INT NOT NULL,
              nb_rdv INT DEFAULT 0 NOT NULL,
              ca_total_ht NUMERIC(12, 2) DEFAULT '0.00' NOT NULL,
              ca_moyen_par_rdv NUMERIC(10, 2) DEFAULT '0.00' NOT NULL,
              dernier_rdv_date DATE DEFAULT NULL,
              jours_depuis_dernier_rdv INT DEFAULT NULL,
              client_segment VARCHAR(50) DEFAULT NULL,
              nb_vehicules INT DEFAULT 0 NOT NULL,
              panier_moyen NUMERIC(10, 2) DEFAULT '0.00' NOT NULL,
              synced_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_client_fact_periode ON analytics_client_facts (
              atelier_id, periode_annee, periode_mois
            )
        SQL);
        $this->addSql('CREATE INDEX idx_client_fact_segment ON analytics_client_facts (atelier_id, client_segment)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uq_client_fact ON analytics_client_facts (
              atelier_id, client_id, periode_annee,
              periode_mois
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_daily_snapshots (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              atelier_id INT NOT NULL,
              snapshot_date DATE NOT NULL,
              nb_rdv_total INT DEFAULT 0 NOT NULL,
              nb_rdv_confirme INT DEFAULT 0 NOT NULL,
              nb_rdv_en_cours INT DEFAULT 0 NOT NULL,
              nb_rdv_termine INT DEFAULT 0 NOT NULL,
              nb_rdv_annule INT DEFAULT 0 NOT NULL,
              nb_or_ouverts INT DEFAULT 0 NOT NULL,
              ca_du_jour_ht NUMERIC(12, 2) DEFAULT '0.00' NOT NULL,
              ca_mo_ht NUMERIC(12, 2) DEFAULT '0.00' NOT NULL,
              ca_pieces_ht NUMERIC(12, 2) DEFAULT '0.00' NOT NULL,
              nb_factures INT DEFAULT 0 NOT NULL,
              panier_moyen NUMERIC(10, 2) DEFAULT '0.00' NOT NULL,
              charge_planifiee_minutes INT DEFAULT 0 NOT NULL,
              charge_effective_minutes INT DEFAULT 0 NOT NULL,
              occupation_ponts_pct INT DEFAULT 0 NOT NULL,
              nb_clients_nouveaux INT DEFAULT 0 NOT NULL,
              nb_clients_recurrents INT DEFAULT 0 NOT NULL,
              nb_devis INT DEFAULT 0 NOT NULL,
              nb_devis_acceptes INT DEFAULT 0 NOT NULL,
              nb_retards_depassement INT DEFAULT 0 NOT NULL,
              nb_attente_restitution INT DEFAULT 0 NOT NULL,
              synced_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uq_snapshot_atelier_date ON analytics_daily_snapshots (atelier_id, snapshot_date)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_rdv_facts (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              atelier_id INT NOT NULL,
              rdv_id INT NOT NULL,
              date_rdv DATE NOT NULL,
              heure_rdv TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              type_intervention VARCHAR(200) DEFAULT NULL,
              statut_rdv VARCHAR(50) NOT NULL,
              client_id INT DEFAULT NULL,
              client_segment VARCHAR(50) DEFAULT NULL,
              vehicule_id INT DEFAULT NULL,
              vehicule_marque VARCHAR(100) DEFAULT NULL,
              vehicule_age_annees INT DEFAULT NULL,
              mecanicien_id INT DEFAULT NULL,
              mecanicien_nom VARCHAR(200) DEFAULT NULL,
              pont_id INT DEFAULT NULL,
              pont_nom VARCHAR(100) DEFAULT NULL,
              temps_estime INT DEFAULT NULL,
              temps_effectif INT DEFAULT NULL,
              prix_estime NUMERIC(10, 2) DEFAULT NULL,
              prix_final NUMERIC(10, 2) DEFAULT NULL,
              ca_ht NUMERIC(10, 2) DEFAULT NULL,
              ca_mo_ht NUMERIC(10, 2) DEFAULT NULL,
              ca_pieces_ht NUMERIC(10, 2) DEFAULT NULL,
              delai_reception_debut INT DEFAULT NULL,
              delai_fin_restitution INT DEFAULT NULL,
              delai_total_cycle INT DEFAULT NULL,
              is_devis_accepte BOOLEAN NOT NULL,
              has_travaux_complementaires BOOLEAN NOT NULL,
              is_facture BOOLEAN NOT NULL,
              is_paye BOOLEAN NOT NULL,
              synced_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_rdv_date ON analytics_rdv_facts (atelier_id, date_rdv)');
        $this->addSql('CREATE INDEX idx_analytics_rdv_statut ON analytics_rdv_facts (atelier_id, statut_rdv)');
        $this->addSql('CREATE INDEX idx_analytics_rdv_meca ON analytics_rdv_facts (atelier_id, mecanicien_id)');
        $this->addSql('CREATE INDEX idx_analytics_rdv_client ON analytics_rdv_facts (atelier_id, client_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE analytics_client_facts');
        $this->addSql('DROP TABLE analytics_daily_snapshots');
        $this->addSql('DROP TABLE analytics_rdv_facts');
    }
}
