<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522162247 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Drop all FK constraints first (PostgreSQL requires this before dropping referenced tables)
        $this->addSql('ALTER TABLE atelier_categorie_motos DROP CONSTRAINT IF EXISTS fk_957914da273b5c0e');
        $this->addSql('ALTER TABLE commandes_fournisseur DROP CONSTRAINT IF EXISTS fk_7b1b2a89670c757f');
        $this->addSql('ALTER TABLE lignes_commande_fournisseur DROP CONSTRAINT IF EXISTS fk_ec5501d1c40fcfa8');
        $this->addSql('ALTER TABLE lignes_commande_fournisseur DROP CONSTRAINT IF EXISTS fk_ec5501d182ea2e54');
        $this->addSql('ALTER TABLE pieces_utilisees DROP CONSTRAINT IF EXISTS fk_a2fc7c3d91ef7eaa');
        $this->addSql('ALTER TABLE pieces_utilisees DROP CONSTRAINT IF EXISTS fk_a2fc7c3dc40fcfa8');
        $this->addSql('ALTER TABLE pont_equipements DROP CONSTRAINT IF EXISTS fk_20a1e73d3f9501f');
        $this->addSql('ALTER TABLE pieces_detachees DROP CONSTRAINT IF EXISTS fk_de693d55670c757f');

        // Drop obsolete tables
        $this->addSql('DROP TABLE IF EXISTS atelier_categorie_motos');
        $this->addSql('DROP TABLE IF EXISTS commandes_fournisseur');
        $this->addSql('DROP TABLE IF EXISTS fournisseurs');
        $this->addSql('DROP TABLE IF EXISTS lignes_commande_fournisseur');
        $this->addSql('DROP TABLE IF EXISTS modules');
        $this->addSql('DROP TABLE IF EXISTS pieces_utilisees');
        $this->addSql('DROP TABLE IF EXISTS pont_equipements');
        $this->addSql('DROP TABLE IF EXISTS user_atelier_roles');

        // Clean up pieces_detachees
        $this->addSql('DROP INDEX IF EXISTS idx_de693d55670c757f');
        $this->addSql('ALTER TABLE pieces_detachees DROP IF EXISTS fournisseur_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE atelier_categorie_motos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, categorie_moto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_957914da273b5c0e ON atelier_categorie_motos (categorie_moto_id)');
        $this->addSql('CREATE TABLE commandes_fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, numero_commande VARCHAR(50) NOT NULL, statut VARCHAR(50) DEFAULT \'en_attente\' NOT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, date_prevue_livraison TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_reception TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_ht NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, total_ttc NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, notes TEXT DEFAULT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_7b1b2a89cffd611d ON commandes_fournisseur (numero_commande)');
        $this->addSql('CREATE INDEX idx_7b1b2a89670c757f ON commandes_fournisseur (fournisseur_id)');
        $this->addSql('CREATE TABLE fournisseurs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, nom VARCHAR(200) NOT NULL, contact VARCHAR(200) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, email VARCHAR(200) DEFAULT NULL, adresse TEXT DEFAULT NULL, siret VARCHAR(20) DEFAULT NULL, delai_livraison_jours INT DEFAULT 3 NOT NULL, notes TEXT DEFAULT NULL, is_active INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lignes_commande_fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atelier_id INT DEFAULT NULL, quantite_demandee INT NOT NULL, quantite_recue INT DEFAULT 0 NOT NULL, prix_unitaire_ht NUMERIC(10, 2) NOT NULL, commande_id INT NOT NULL, piece_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ec5501d1c40fcfa8 ON lignes_commande_fournisseur (piece_id)');
        $this->addSql('CREATE INDEX idx_ec5501d182ea2e54 ON lignes_commande_fournisseur (commande_id)');
        $this->addSql('CREATE TABLE modules (code VARCHAR(50) NOT NULL, libelle VARCHAR(120) NOT NULL, actions JSON NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE pieces_utilisees (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_vente_unitaire NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, rendez_vous_id INT NOT NULL, piece_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_a2fc7c3d91ef7eaa ON pieces_utilisees (rendez_vous_id)');
        $this->addSql('CREATE INDEX idx_a2fc7c3dc40fcfa8 ON pieces_utilisees (piece_id)');
        $this->addSql('CREATE TABLE pont_equipements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, is_present BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, pont_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_20a1e73d3f9501f ON pont_equipements (pont_id)');
        $this->addSql('CREATE TABLE user_atelier_roles (user_id INT NOT NULL, atelier_id INT NOT NULL, role VARCHAR(50) DEFAULT \'receptionnaire\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (user_id, atelier_id))');
        $this->addSql('ALTER TABLE atelier_categorie_motos ADD CONSTRAINT fk_957914da273b5c0e FOREIGN KEY (categorie_moto_id) REFERENCES categorie_motos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commandes_fournisseur ADD CONSTRAINT fk_7b1b2a89670c757f FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lignes_commande_fournisseur ADD CONSTRAINT fk_ec5501d1c40fcfa8 FOREIGN KEY (piece_id) REFERENCES pieces_detachees (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lignes_commande_fournisseur ADD CONSTRAINT fk_ec5501d182ea2e54 FOREIGN KEY (commande_id) REFERENCES commandes_fournisseur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pieces_utilisees ADD CONSTRAINT fk_a2fc7c3d91ef7eaa FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pieces_utilisees ADD CONSTRAINT fk_a2fc7c3dc40fcfa8 FOREIGN KEY (piece_id) REFERENCES pieces_detachees (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pont_equipements ADD CONSTRAINT fk_20a1e73d3f9501f FOREIGN KEY (pont_id) REFERENCES ponts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pieces_detachees ADD fournisseur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pieces_detachees ADD CONSTRAINT fk_de693d55670c757f FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_de693d55670c757f ON pieces_detachees (fournisseur_id)');
    }
}
