<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417033458 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification_escalations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, channel VARCHAR(20) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, executed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, result VARCHAR(30) DEFAULT NULL, skip_reason VARCHAR(100) DEFAULT NULL, target_info VARCHAR(500) DEFAULT NULL, notification_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4F757552EF1A9D84 ON notification_escalations (notification_id)');
        $this->addSql('CREATE INDEX idx_escalation_schedule ON notification_escalations (scheduled_at, executed_at)');
        $this->addSql('ALTER TABLE notification_escalations ADD CONSTRAINT FK_4F757552EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demandes_travaux_supp DROP CONSTRAINT fk_demande_or_comp');
        $this->addSql('ALTER TABLE demandes_travaux_supp ALTER prestations_choisies DROP DEFAULT');
        $this->addSql('ALTER TABLE demandes_travaux_supp ADD CONSTRAINT FK_E1AFBD37D1B34E6E FOREIGN KEY (or_complementaire_id) REFERENCES ordres_reparation (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_demande_token RENAME TO UNIQ_E1AFBD37FE604AD0');
        $this->addSql('DROP INDEX idx_notif_atelier_read');
        $this->addSql('DROP INDEX idx_notif_target_user');
        $this->addSql('ALTER TABLE notifications ADD severity VARCHAR(20) DEFAULT \'info\' NOT NULL');
        $this->addSql('ALTER TABLE notifications ADD title VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE notifications ADD action_url VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD related_entity_type VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD read_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD acknowledged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD acknowledged_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER target_roles DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications RENAME COLUMN entity_type TO target_role');
        $this->addSql('ALTER TABLE notifications RENAME COLUMN entity_id TO related_entity_id');
        $this->addSql('CREATE INDEX idx_notif_atelier_ack ON notifications (atelier_id, acknowledged_at)');
        $this->addSql('CREATE INDEX idx_notif_user_read ON notifications (target_user_id, read_at)');
        $this->addSql('ALTER TABLE ordres_reparation DROP CONSTRAINT fk_or_rectified_from');
        $this->addSql('DROP INDEX idx_or_statut');
        $this->addSql('ALTER TABLE ordres_reparation ADD CONSTRAINT FK_20160E34A08AA53C FOREIGN KEY (rectified_from_id) REFERENCES ordres_reparation (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_or_rectified_from RENAME TO IDX_20160E34A08AA53C');
        $this->addSql('ALTER INDEX uq_rpe_role_module_action RENAME TO UNIQ_37AB54D8BCE229FCC24262847CC8C92');
        $this->addSql('ALTER TABLE roles_metier ALTER base_role DROP DEFAULT');
        $this->addSql('ALTER INDEX uq_roles_metier_atelier_code RENAME TO UNIQ_BA8738ED82E2CF3577153098');
        $this->addSql('ALTER INDEX idx_users_role_metier RENAME TO IDX_1483A5E9BCE229FC');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification_escalations DROP CONSTRAINT FK_4F757552EF1A9D84');
        $this->addSql('DROP TABLE notification_escalations');
        $this->addSql('ALTER TABLE demandes_travaux_supp DROP CONSTRAINT FK_E1AFBD37D1B34E6E');
        $this->addSql('ALTER TABLE demandes_travaux_supp ALTER prestations_choisies SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE demandes_travaux_supp ADD CONSTRAINT fk_demande_or_comp FOREIGN KEY (or_complementaire_id) REFERENCES ordres_reparation (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX uniq_e1afbd37fe604ad0 RENAME TO uniq_demande_token');
        $this->addSql('DROP INDEX idx_notif_atelier_ack');
        $this->addSql('DROP INDEX idx_notif_user_read');
        $this->addSql('ALTER TABLE notifications ADD entity_type VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD entity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications DROP target_role');
        $this->addSql('ALTER TABLE notifications DROP severity');
        $this->addSql('ALTER TABLE notifications DROP title');
        $this->addSql('ALTER TABLE notifications DROP action_url');
        $this->addSql('ALTER TABLE notifications DROP related_entity_type');
        $this->addSql('ALTER TABLE notifications DROP related_entity_id');
        $this->addSql('ALTER TABLE notifications DROP read_at');
        $this->addSql('ALTER TABLE notifications DROP read_by');
        $this->addSql('ALTER TABLE notifications DROP acknowledged_at');
        $this->addSql('ALTER TABLE notifications DROP acknowledged_by');
        $this->addSql('ALTER TABLE notifications DROP expires_at');
        $this->addSql('ALTER TABLE notifications ALTER id SET DEFAULT nextval(\'notifications_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE notifications ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER target_roles SET DEFAULT \'[]\'');
        $this->addSql('CREATE INDEX idx_notif_atelier_read ON notifications (atelier_id, is_read)');
        $this->addSql('CREATE INDEX idx_notif_target_user ON notifications (target_user_id)');
        $this->addSql('ALTER TABLE ordres_reparation DROP CONSTRAINT FK_20160E34A08AA53C');
        $this->addSql('ALTER TABLE ordres_reparation ADD CONSTRAINT fk_or_rectified_from FOREIGN KEY (rectified_from_id) REFERENCES ordres_reparation (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_or_statut ON ordres_reparation (statut)');
        $this->addSql('ALTER INDEX idx_20160e34a08aa53c RENAME TO idx_or_rectified_from');
        $this->addSql('ALTER INDEX uniq_37ab54d8bce229fcc24262847cc8c92 RENAME TO uq_rpe_role_module_action');
        $this->addSql('ALTER TABLE roles_metier ALTER base_role SET DEFAULT \'ROLE_USER\'');
        $this->addSql('ALTER INDEX uniq_ba8738ed82e2cf3577153098 RENAME TO uq_roles_metier_atelier_code');
        $this->addSql('ALTER INDEX idx_1483a5e9bce229fc RENAME TO idx_users_role_metier');
    }
}
