
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AppBanner: typeof import("../../components/AppBanner.vue")['default']
  AppBreadcrumbs: typeof import("../../components/AppBreadcrumbs.vue")['default']
  AppEmptyState: typeof import("../../components/AppEmptyState.vue")['default']
  AppErrorState: typeof import("../../components/AppErrorState.vue")['default']
  AppKpiSkeleton: typeof import("../../components/AppKpiSkeleton.vue")['default']
  AppLoadingState: typeof import("../../components/AppLoadingState.vue")['default']
  AppModal: typeof import("../../components/AppModal.vue")['default']
  AppNotificationBell: typeof import("../../components/AppNotificationBell.vue")['default']
  AppNotificationPopIn: typeof import("../../components/AppNotificationPopIn.vue")['default']
  AppPageHeader: typeof import("../../components/AppPageHeader.vue")['default']
  AppPeriodSelector: typeof import("../../components/AppPeriodSelector.vue")['default']
  AppQuickActions: typeof import("../../components/AppQuickActions.vue")['default']
  AppSidebarLink: typeof import("../../components/AppSidebarLink.vue")['default']
  AppSkeletonCard: typeof import("../../components/AppSkeletonCard.vue")['default']
  AppSkeletonTable: typeof import("../../components/AppSkeletonTable.vue")['default']
  AppStatsCard: typeof import("../../components/AppStatsCard.vue")['default']
  AppTable: typeof import("../../components/AppTable.vue")['default']
  BaseBadge: typeof import("../../components/BaseBadge.vue")['default']
  BaseKpi: typeof import("../../components/BaseKpi.vue")['default']
  BaseStatus: typeof import("../../components/BaseStatus.vue")['default']
  MecanicienCheckupGrid: typeof import("../../components/MecanicienCheckupGrid.vue")['default']
  MecanicienChrono: typeof import("../../components/MecanicienChrono.vue")['default']
  MecanicienNav: typeof import("../../components/MecanicienNav.vue")['default']
  MecanicienSection: typeof import("../../components/MecanicienSection.vue")['default']
  PlanningGrid: typeof import("../../components/PlanningGrid.vue")['default']
  PlanningGridCell: typeof import("../../components/PlanningGridCell.vue")['default']
  PlanningGridHeader: typeof import("../../components/PlanningGridHeader.vue")['default']
  PlanningGridMecanoRow: typeof import("../../components/PlanningGridMecanoRow.vue")['default']
  PlanningList: typeof import("../../components/PlanningList.vue")['default']
  UTable: typeof import("../../components/UTable.vue")['default']
  PlanningGridShared: typeof import("../../components/planning-grid-shared")['default']
  VOCompanionCard: typeof import("../../components/vo/VOCompanionCard.vue")['default']
  VODossierTypes: typeof import("../../components/vo/VODossier.types")['default']
  VODossierDocumentList: typeof import("../../components/vo/VODossierDocumentList.vue")['default']
  VODossierIdentity: typeof import("../../components/vo/VODossierIdentity.vue")['default']
  VODossierMotoCard: typeof import("../../components/vo/VODossierMotoCard.vue")['default']
  VODossierScanPanel: typeof import("../../components/vo/VODossierScanPanel.vue")['default']
  VODossierUploadPanel: typeof import("../../components/vo/VODossierUploadPanel.vue")['default']
  VODossierVerdict: typeof import("../../components/vo/VODossierVerdict.vue")['default']
  VONav: typeof import("../../components/vo/VONav.vue")['default']
  VORemiseEnEtatCard: typeof import("../../components/vo/VORemiseEnEtatCard.vue")['default']
  VORemiseEnEtatForm: typeof import("../../components/vo/VORemiseEnEtatForm.vue")['default']
  VORemiseEnEtatPieces: typeof import("../../components/vo/VORemiseEnEtatPieces.vue")['default']
  VORemiseEnEtatPrestations: typeof import("../../components/vo/VORemiseEnEtatPrestations.vue")['default']
  VORemiseEnEtatSidebar: typeof import("../../components/vo/VORemiseEnEtatSidebar.vue")['default']
  VORemiseEnEtatSignature: typeof import("../../components/vo/VORemiseEnEtatSignature.vue")['default']
  VORemiseEnEtatSummary: typeof import("../../components/vo/VORemiseEnEtatSummary.vue")['default']
  WorkshopActionMenu: typeof import("../../components/workshop/WorkshopActionMenu.vue")['default']
  WorkshopAlertBadges: typeof import("../../components/workshop/WorkshopAlertBadges.vue")['default']
  WorkshopSkeletonBays: typeof import("../../components/workshop/WorkshopSkeletonBays.vue")['default']
  WorkshopVehicleTimeline: typeof import("../../components/workshop/WorkshopVehicleTimeline.vue")['default']
  UAccordion: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']
  UAlert: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']
  UApp: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']
  UAvatar: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']
  UAvatarGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']
  UBadge: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']
  UBreadcrumb: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']
  UButton: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']
  UButtonGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue")['default']
  UCalendar: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']
  UCard: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']
  UCarousel: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']
  UCheckbox: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']
  UCheckboxGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']
  UChip: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']
  UCollapsible: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']
  UColorPicker: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']
  UCommandPalette: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']
  UContainer: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']
  UContextMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']
  UContextMenuContent: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']
  UDrawer: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']
  UDropdownMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']
  UDropdownMenuContent: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']
  UFileUpload: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']
  UForm: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']
  UFormField: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']
  UIcon: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']
  UInput: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']
  UInputMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']
  UInputNumber: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']
  UInputTags: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']
  UKbd: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']
  ULink: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']
  ULinkBase: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']
  UModal: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']
  UNavigationMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']
  UOverlayProvider: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']
  UPagination: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']
  UPinInput: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']
  UPopover: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']
  UProgress: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']
  URadioGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']
  USelect: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']
  USelectMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']
  USeparator: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']
  USkeleton: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']
  USlideover: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']
  USlider: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']
  UStepper: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']
  USwitch: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']
  UTabs: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']
  UTextarea: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']
  UTimeline: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']
  UToast: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']
  UToaster: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']
  UTooltip: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']
  UTree: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  Icon: typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  ColorScheme: typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAppBanner: LazyComponent<typeof import("../../components/AppBanner.vue")['default']>
  LazyAppBreadcrumbs: LazyComponent<typeof import("../../components/AppBreadcrumbs.vue")['default']>
  LazyAppEmptyState: LazyComponent<typeof import("../../components/AppEmptyState.vue")['default']>
  LazyAppErrorState: LazyComponent<typeof import("../../components/AppErrorState.vue")['default']>
  LazyAppKpiSkeleton: LazyComponent<typeof import("../../components/AppKpiSkeleton.vue")['default']>
  LazyAppLoadingState: LazyComponent<typeof import("../../components/AppLoadingState.vue")['default']>
  LazyAppModal: LazyComponent<typeof import("../../components/AppModal.vue")['default']>
  LazyAppNotificationBell: LazyComponent<typeof import("../../components/AppNotificationBell.vue")['default']>
  LazyAppNotificationPopIn: LazyComponent<typeof import("../../components/AppNotificationPopIn.vue")['default']>
  LazyAppPageHeader: LazyComponent<typeof import("../../components/AppPageHeader.vue")['default']>
  LazyAppPeriodSelector: LazyComponent<typeof import("../../components/AppPeriodSelector.vue")['default']>
  LazyAppQuickActions: LazyComponent<typeof import("../../components/AppQuickActions.vue")['default']>
  LazyAppSidebarLink: LazyComponent<typeof import("../../components/AppSidebarLink.vue")['default']>
  LazyAppSkeletonCard: LazyComponent<typeof import("../../components/AppSkeletonCard.vue")['default']>
  LazyAppSkeletonTable: LazyComponent<typeof import("../../components/AppSkeletonTable.vue")['default']>
  LazyAppStatsCard: LazyComponent<typeof import("../../components/AppStatsCard.vue")['default']>
  LazyAppTable: LazyComponent<typeof import("../../components/AppTable.vue")['default']>
  LazyBaseBadge: LazyComponent<typeof import("../../components/BaseBadge.vue")['default']>
  LazyBaseKpi: LazyComponent<typeof import("../../components/BaseKpi.vue")['default']>
  LazyBaseStatus: LazyComponent<typeof import("../../components/BaseStatus.vue")['default']>
  LazyMecanicienCheckupGrid: LazyComponent<typeof import("../../components/MecanicienCheckupGrid.vue")['default']>
  LazyMecanicienChrono: LazyComponent<typeof import("../../components/MecanicienChrono.vue")['default']>
  LazyMecanicienNav: LazyComponent<typeof import("../../components/MecanicienNav.vue")['default']>
  LazyMecanicienSection: LazyComponent<typeof import("../../components/MecanicienSection.vue")['default']>
  LazyPlanningGrid: LazyComponent<typeof import("../../components/PlanningGrid.vue")['default']>
  LazyPlanningGridCell: LazyComponent<typeof import("../../components/PlanningGridCell.vue")['default']>
  LazyPlanningGridHeader: LazyComponent<typeof import("../../components/PlanningGridHeader.vue")['default']>
  LazyPlanningGridMecanoRow: LazyComponent<typeof import("../../components/PlanningGridMecanoRow.vue")['default']>
  LazyPlanningList: LazyComponent<typeof import("../../components/PlanningList.vue")['default']>
  LazyUTable: LazyComponent<typeof import("../../components/UTable.vue")['default']>
  LazyPlanningGridShared: LazyComponent<typeof import("../../components/planning-grid-shared")['default']>
  LazyVOCompanionCard: LazyComponent<typeof import("../../components/vo/VOCompanionCard.vue")['default']>
  LazyVODossierTypes: LazyComponent<typeof import("../../components/vo/VODossier.types")['default']>
  LazyVODossierDocumentList: LazyComponent<typeof import("../../components/vo/VODossierDocumentList.vue")['default']>
  LazyVODossierIdentity: LazyComponent<typeof import("../../components/vo/VODossierIdentity.vue")['default']>
  LazyVODossierMotoCard: LazyComponent<typeof import("../../components/vo/VODossierMotoCard.vue")['default']>
  LazyVODossierScanPanel: LazyComponent<typeof import("../../components/vo/VODossierScanPanel.vue")['default']>
  LazyVODossierUploadPanel: LazyComponent<typeof import("../../components/vo/VODossierUploadPanel.vue")['default']>
  LazyVODossierVerdict: LazyComponent<typeof import("../../components/vo/VODossierVerdict.vue")['default']>
  LazyVONav: LazyComponent<typeof import("../../components/vo/VONav.vue")['default']>
  LazyVORemiseEnEtatCard: LazyComponent<typeof import("../../components/vo/VORemiseEnEtatCard.vue")['default']>
  LazyVORemiseEnEtatForm: LazyComponent<typeof import("../../components/vo/VORemiseEnEtatForm.vue")['default']>
  LazyVORemiseEnEtatPieces: LazyComponent<typeof import("../../components/vo/VORemiseEnEtatPieces.vue")['default']>
  LazyVORemiseEnEtatPrestations: LazyComponent<typeof import("../../components/vo/VORemiseEnEtatPrestations.vue")['default']>
  LazyVORemiseEnEtatSidebar: LazyComponent<typeof import("../../components/vo/VORemiseEnEtatSidebar.vue")['default']>
  LazyVORemiseEnEtatSignature: LazyComponent<typeof import("../../components/vo/VORemiseEnEtatSignature.vue")['default']>
  LazyVORemiseEnEtatSummary: LazyComponent<typeof import("../../components/vo/VORemiseEnEtatSummary.vue")['default']>
  LazyWorkshopActionMenu: LazyComponent<typeof import("../../components/workshop/WorkshopActionMenu.vue")['default']>
  LazyWorkshopAlertBadges: LazyComponent<typeof import("../../components/workshop/WorkshopAlertBadges.vue")['default']>
  LazyWorkshopSkeletonBays: LazyComponent<typeof import("../../components/workshop/WorkshopSkeletonBays.vue")['default']>
  LazyWorkshopVehicleTimeline: LazyComponent<typeof import("../../components/workshop/WorkshopVehicleTimeline.vue")['default']>
  LazyUAccordion: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']>
  LazyUAlert: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']>
  LazyUApp: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']>
  LazyUAvatar: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']>
  LazyUAvatarGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']>
  LazyUBadge: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']>
  LazyUBreadcrumb: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']>
  LazyUButton: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']>
  LazyUButtonGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue")['default']>
  LazyUCalendar: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']>
  LazyUCard: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']>
  LazyUCarousel: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']>
  LazyUCheckbox: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']>
  LazyUCheckboxGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']>
  LazyUChip: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']>
  LazyUCollapsible: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']>
  LazyUColorPicker: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']>
  LazyUCommandPalette: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']>
  LazyUContainer: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']>
  LazyUContextMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']>
  LazyUContextMenuContent: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']>
  LazyUDrawer: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']>
  LazyUDropdownMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']>
  LazyUDropdownMenuContent: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']>
  LazyUFileUpload: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']>
  LazyUForm: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']>
  LazyUFormField: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']>
  LazyUIcon: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']>
  LazyUInput: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']>
  LazyUInputMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']>
  LazyUInputNumber: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']>
  LazyUInputTags: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']>
  LazyUKbd: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']>
  LazyULink: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']>
  LazyULinkBase: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']>
  LazyUModal: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']>
  LazyUNavigationMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']>
  LazyUOverlayProvider: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']>
  LazyUPagination: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']>
  LazyUPinInput: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']>
  LazyUPopover: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']>
  LazyUProgress: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']>
  LazyURadioGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']>
  LazyUSelect: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']>
  LazyUSelectMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']>
  LazyUSeparator: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']>
  LazyUSkeleton: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']>
  LazyUSlideover: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']>
  LazyUSlider: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']>
  LazyUStepper: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']>
  LazyUSwitch: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']>
  LazyUTabs: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']>
  LazyUTextarea: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']>
  LazyUTimeline: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']>
  LazyUToast: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']>
  LazyUToaster: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']>
  LazyUTooltip: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']>
  LazyUTree: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyIcon: LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  LazyColorScheme: LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
